import { l } from "../_helpers";
import type { ActivityInfo, Localized, Place } from "@/lib/types";

/**
 * ─────────────────────────────────────────────────────────────────────────────
 *  BEACHES, SNORKELING, DIVING, NATURE & ACTIVITIES
 *  ⚠️ DEMO CONTENT — well-known Bonaire places with general, non-committal
 *  descriptions. Coordinates are APPROXIMATE (route buttons use the name
 *  search instead). Verify every entry, then remove `demo: true`.
 *  Do not add fees, times or rules unless they are verified.
 * ─────────────────────────────────────────────────────────────────────────────
 */

const act = (a: Record<keyof ActivityInfo, [string, string]>): ActivityInfo =>
  Object.fromEntries(Object.entries(a).map(([k, [nl, en]]) => [k, { nl, en } as Localized])) as unknown as ActivityInfo;

export const beaches: Place[] = [
  {
    id: "klein-bonaire",
    demo: true,
    category: "beaches",
    alsoIn: ["snorkeling", "activities"],
    name: "Klein Bonaire",
    art: "beach",
    area: l("Tegenover Kralendijk", "Opposite Kralendijk"),
    mapsQuery: "No Name Beach Klein Bonaire",
    coordinates: { lat: 12.1600, lng: -68.3130, approximate: true },
    favorite: true,
    tags: ["favorite", "snorkeling", "nature", "worth-the-drive"],
    summary: l("Een onbewoond eilandje met wit zand en helder water, met de watertaxi of boot bereikbaar.", "An uninhabited islet with white sand and clear water, reached by water taxi or boat."),
    whyWeRecommend: l("Het voelt als je eigen eiland. Neem je snorkel mee en genoeg water.", "It feels like your own private island. Bring your snorkel and plenty of water."),
    tip: l("Er is geen schaduw en geen voorzieningen — neem alles zelf mee en neem alles weer mee terug.", "There's no shade and no facilities — bring everything and take everything back."),
    activity: act({
      why: ["Wit strand, rust en een prachtig rif vlak voor de kust.", "White sand, peace and a beautiful reef just off the beach."],
      forWho: ["Iedereen die van snorkelen en rust houdt.", "Anyone who loves snorkeling and quiet."],
      duration: ["Een halve dag.", "Half a day."],
      bring: ["Water, snacks, zonnebrand (rifvriendelijk), schaduw, snorkelset.", "Water, snacks, reef-safe sunscreen, some shade, snorkel gear."],
      bestTime: ["Ochtend, als het nog rustig is.", "Morning, while it's still quiet."],
      diyOrBook: ["Watertaxi boeken — of met de boot van Kas Daas.", "Book a water taxi — or go with the Kas Daas boat."],
      keepInMind: ["Beschermd natuurgebied: niets meenemen, niets achterlaten.", "Protected nature: take nothing, leave nothing."],
    }),
    keywords: ["klein bonaire", "no name beach", "eiland", "island", "watertaxi", "water taxi", "strand", "beach", "snorkelen"],
  },
  {
    id: "sorobon",
    demo: true,
    category: "beaches",
    alsoIn: ["kids", "activities"],
    name: "Sorobon & Lac Bay",
    art: "wind",
    area: l("Oostkust", "East coast"),
    mapsQuery: "Sorobon Beach Bonaire",
    coordinates: { lat: 12.1040, lng: -68.2280, approximate: true },
    favorite: true,
    tags: ["favorite", "family", "after-the-beach", "active"],
    summary: l("Een ondiepe, turquoise baai — de plek voor windsurfen en rustig pootje baden.", "A shallow turquoise bay — the place for windsurfing and gentle paddling."),
    whyWeRecommend: l("Het water is er ondiep en kalm: heerlijk met kinderen en prachtig om naar te kijken.", "The water is shallow and calm: wonderful with children and beautiful to look at."),
    activity: act({
      why: ["Kalm ondiep water, strandbars en windsurfers om naar te kijken.", "Calm shallow water, beach bars and windsurfers to watch."],
      forWho: ["Gezinnen, windsurfers en iedereen die wil luieren.", "Families, windsurfers and anyone who wants to laze."],
      duration: ["Een halve tot hele dag.", "Half a day to a full day."],
      bring: ["Zonnebrand, waterschoenen, geld voor lunch.", "Sunscreen, water shoes, money for lunch."],
      bestTime: ["Ochtend voor rust, middag voor de wind.", "Morning for calm, afternoon for wind."],
      diyOrBook: ["Zelf doen; windsurfles boek je ter plekke.", "DIY; windsurf lessons can be booked on site."],
      keepInMind: ["De zon is fel en er is weinig natuurlijke schaduw.", "The sun is strong and there's little natural shade."],
    }),
    keywords: ["sorobon", "lac bay", "lac", "strand", "beach", "windsurfen", "windsurfing", "kinderen", "kids"],
  },
  {
    id: "te-amo-beach",
    demo: true,
    category: "beaches",
    alsoIn: ["snorkeling", "sunset"],
    name: "Te Amo Beach",
    art: "beach",
    area: l("Bij het vliegveld", "Near the airport"),
    mapsQuery: "Te Amo Beach Bonaire",
    coordinates: { lat: 12.1250, lng: -68.2830, approximate: true },
    tags: ["sunset", "snorkeling", "quick-bite"],
    summary: l("Klein strandje aan de westkust waar je vliegtuigen laag ziet overkomen.", "Small west-coast beach where planes fly in low overhead."),
    whyWeRecommend: l("Makkelijk bereikbaar, fijn voor een snelle duik en mooi bij zonsondergang.", "Easy to reach, great for a quick dip and lovely at sunset."),
    keywords: ["te amo", "strand", "beach", "vliegtuig", "airplane", "sunset"],
  },
  {
    id: "pink-beach",
    demo: true,
    category: "beaches",
    alsoIn: ["snorkeling", "roadtrips"],
    name: "Pink Beach",
    art: "salt",
    area: l("Zuiden", "South"),
    mapsQuery: "Pink Beach Bonaire",
    coordinates: { lat: 12.0650, lng: -68.2830, approximate: true },
    tags: ["worth-the-drive", "snorkeling", "nature"],
    summary: l("Lang, rustig strand in het zuiden met een roze gloed in het zand.", "Long, quiet beach in the south with a pink glow in the sand."),
    whyWeRecommend: l("Combineer het met de zoutpannen en slavenhuisjes voor een mooi dagje zuiden.", "Combine it with the salt pans and slave huts for a lovely day in the south."),
    tip: l("Er is geen schaduw — neem een parasol mee.", "There's no shade — bring an umbrella."),
    keywords: ["pink beach", "roze", "pink", "strand", "beach", "zuiden", "south"],
  },
  {
    id: "lac-cai",
    demo: true,
    category: "beaches",
    alsoIn: ["hidden-gems"],
    name: "Lac Cai",
    art: "sea",
    area: l("Oostkust", "East coast"),
    mapsQuery: "Lac Cai Bonaire",
    coordinates: { lat: 12.0980, lng: -68.2150, approximate: true },
    tags: ["local", "nature"],
    summary: l("Aan de andere kant van Lac Bay, geliefd bij locals in het weekend.", "On the far side of Lac Bay, loved by locals at weekends."),
    whyWeRecommend: l("Een stuk echte eilandcultuur, met stapels schelpen en mangroves onderweg.", "A slice of real island life, with piles of conch shells and mangroves on the way."),
    keywords: ["lac cai", "local", "lokaal", "strand", "beach", "schelpen", "conch"],
  },
];

export const underwater: Place[] = [
  {
    id: "1000-steps",
    demo: true,
    category: "snorkeling",
    alsoIn: ["diving", "hidden-gems"],
    name: "1000 Steps",
    art: "reef",
    area: l("Noordwestkust", "North-west coast"),
    mapsQuery: "1000 Steps Bonaire",
    coordinates: { lat: 12.2150, lng: -68.3350, approximate: true },
    favorite: true,
    tags: ["favorite", "snorkeling", "diving", "worth-the-drive"],
    summary: l("Een trap naar een klein strand met een van de mooiste riffen vlak onder de kust.", "A staircase down to a small beach with one of the most beautiful reefs right offshore."),
    whyWeRecommend: l("Het zijn er geen duizend — maar na het snorkelen voelt de weg naar boven wel zo.", "It's not really a thousand steps — but after snorkeling the climb back up feels like it."),
    activity: act({
      why: ["Helder water, veel vis en koraal direct vanaf het strand.", "Clear water, lots of fish and coral straight from the beach."],
      forWho: ["Snorkelaars en duikers met enige ervaring.", "Snorkelers and divers with some experience."],
      duration: ["2–3 uur.", "2–3 hours."],
      bring: ["Snorkelset, waterschoenen, water, rifvriendelijke zonnebrand.", "Snorkel gear, water shoes, water, reef-safe sunscreen."],
      bestTime: ["Ochtend, als het licht mooi is en het rustig is.", "Morning, when the light is beautiful and it's quiet."],
      diyOrBook: ["Zelf doen.", "DIY."],
      keepInMind: ["Raak het koraal niet aan en laat niets in de auto liggen.", "Don't touch the coral and leave nothing in the car."],
    }),
    keywords: ["1000 steps", "thousand steps", "snorkelen", "snorkeling", "duiken", "diving", "rif", "reef", "koraal", "coral"],
  },
  {
    id: "andrea",
    demo: true,
    category: "snorkeling",
    alsoIn: ["diving"],
    name: "Andrea I & II",
    art: "reef",
    area: l("Noord van Kralendijk", "North of Kralendijk"),
    mapsQuery: "Andrea I dive site Bonaire",
    coordinates: { lat: 12.1880, lng: -68.2960, approximate: true },
    tags: ["snorkeling", "diving"],
    summary: l("Twee rustige stekken naast elkaar met makkelijke instap.", "Two quiet neighbouring sites with an easy entry."),
    whyWeRecommend: l("Fijn voor een eerste snorkel op Bonaire om te wennen.", "Great for your first snorkel on Bonaire to get used to it."),
    keywords: ["andrea", "snorkelen", "snorkeling", "duiken", "diving", "makkelijk", "easy"],
  },
  {
    id: "salt-pier",
    demo: true,
    category: "diving",
    alsoIn: ["snorkeling"],
    name: "Salt Pier",
    art: "reef",
    area: l("Zuiden", "South"),
    mapsQuery: "Salt Pier Bonaire",
    coordinates: { lat: 12.0830, lng: -68.2840, approximate: true },
    tags: ["diving", "snorkeling"],
    summary: l("Onder de zoutpier zie je lichtstralen tussen begroeide pilaren — iconisch.", "Beneath the salt pier, light beams through overgrown pillars — iconic."),
    whyWeRecommend: l("Een van de meest fotogenieke duikplekken van het eiland.", "One of the most photogenic dive spots on the island."),
    tip: l("Duiken/snorkelen is niet altijd toegestaan (bijv. als er een schip ligt). Check dit vooraf.", "Diving/snorkeling isn't always allowed (e.g. when a ship is docked). Check before you go."),
    keywords: ["salt pier", "zoutpier", "duiken", "diving", "snorkelen", "pier"],
  },
  {
    id: "hilma-hooker",
    demo: true,
    category: "diving",
    name: "Hilma Hooker",
    art: "reef",
    area: l("Zuid van Kralendijk", "South of Kralendijk"),
    mapsQuery: "Hilma Hooker wreck Bonaire",
    coordinates: { lat: 12.1130, lng: -68.2850, approximate: true },
    tags: ["diving"],
    summary: l("Een beroemd scheepswrak op diepte, voor ervaren duikers.", "A famous shipwreck at depth, for experienced divers."),
    whyWeRecommend: l("Een indrukwekkende wrakduik — het liefst met een lokale duikschool.", "An impressive wreck dive — ideally with a local dive school."),
    keywords: ["hilma hooker", "wrak", "wreck", "duiken", "diving"],
  },
];

export const activities: Place[] = [
  {
    id: "washington-slagbaai",
    demo: true,
    category: "nature",
    alsoIn: ["activities", "roadtrips", "hidden-gems"],
    name: "Washington Slagbaai National Park",
    art: "nature",
    area: l("Noorden", "North"),
    mapsQuery: "Washington Slagbaai National Park Visitor Center",
    coordinates: { lat: 12.2930, lng: -68.3950, approximate: true },
    favorite: true,
    tags: ["favorite", "nature", "worth-the-drive", "active"],
    summary: l("Ruig natuurpark met cactussen, kliffen, verlaten baaien en flamingo's.", "Rugged national park with cacti, cliffs, deserted bays and flamingos."),
    whyWeRecommend: l("Hier zie je het wilde Bonaire. Een dag die je niet snel vergeet.", "This is wild Bonaire. A day you won't soon forget."),
    activity: act({
      why: ["Ongerepte natuur, uitzichtpunten en afgelegen snorkelbaaien.", "Untouched nature, viewpoints and remote snorkel bays."],
      forWho: ["Avonturiers en natuurliefhebbers.", "Adventurers and nature lovers."],
      duration: ["Een (halve) dag.", "Half a day to a full day."],
      bring: ["Veel water, eten, zonnebrand, snorkelset, volle tank.", "Plenty of water, food, sunscreen, snorkel gear, a full tank."],
      bestTime: ["Vroeg in de ochtend vertrekken.", "Leave early in the morning."],
      diyOrBook: ["Zelf rijden (liefst met een hogere auto) of een tour boeken.", "Drive yourself (ideally a higher car) or book a tour."],
      keepInMind: ["Controleer vooraf openingstijden, toegang en wegen.", "Check opening hours, entry and road conditions beforehand."],
    }),
    keywords: ["washington", "slagbaai", "park", "nationaal park", "national park", "natuur", "nature", "wandelen", "hiking"],
  },
  {
    id: "salt-pans-slave-huts",
    demo: true,
    category: "roadtrips",
    alsoIn: ["activities", "sunset"],
    name: l("Zoutpannen & slavenhuisjes", "Salt pans & slave huts"),
    art: "salt",
    area: l("Zuiden", "South"),
    mapsQuery: "Slave Huts Bonaire",
    coordinates: { lat: 12.0480, lng: -68.2750, approximate: true },
    favorite: true,
    tags: ["favorite", "worth-the-drive", "sunset", "nature"],
    summary: l("Roze zoutvlaktes, witte zoutbergen en de indrukwekkende slavenhuisjes.", "Pink salt flats, white salt mountains and the moving slave huts."),
    whyWeRecommend: l("Prachtig licht en een stukje geschiedenis dat je moet zien.", "Beautiful light and a piece of history you should see."),
    activity: act({
      why: ["Surrealistische kleuren en een indrukwekkend stuk geschiedenis.", "Surreal colours and a moving piece of history."],
      forWho: ["Iedereen — ook met kinderen.", "Everyone — kids included."],
      duration: ["1–2 uur rijden en stoppen.", "1–2 hours of driving and stopping."],
      bring: ["Camera, water, zonnebril.", "Camera, water, sunglasses."],
      bestTime: ["Laat in de middag voor het mooiste licht.", "Late afternoon for the best light."],
      diyOrBook: ["Zelf rijden.", "Drive yourself."],
      keepInMind: ["Blijf op de weg; de zoutpannen zijn een werkend bedrijf en natuurgebied.", "Stay on the road; the salt pans are a working business and a nature area."],
    }),
    keywords: ["zoutpannen", "salt pans", "zout", "salt", "slavenhuisjes", "slave huts", "roze", "pink", "zuiden", "south", "geschiedenis", "history"],
  },
  {
    id: "flamingos",
    demo: true,
    category: "nature",
    alsoIn: ["activities", "kids"],
    name: l("Flamingo's bij Gotomeer", "Flamingos at Gotomeer"),
    art: "flamingo",
    area: l("Noorden", "North"),
    mapsQuery: "Gotomeer Bonaire",
    coordinates: { lat: 12.2300, lng: -68.3700, approximate: true },
    tags: ["nature", "family"],
    summary: l("Een meer in het noorden waar je vaak flamingo's ziet foerageren.", "A lake in the north where flamingos are often seen feeding."),
    whyWeRecommend: l("Onderweg naar Rincon of het park: even stoppen en genieten.", "On the way to Rincon or the park: stop for a moment and enjoy."),
    tip: l("Houd afstand en wees stil — flamingo's schrikken snel.", "Keep your distance and stay quiet — flamingos startle easily."),
    keywords: ["flamingo", "flamingos", "gotomeer", "vogels", "birds", "wildlife"],
  },
  {
    id: "mangroves",
    demo: true,
    category: "activities",
    alsoIn: ["nature", "kids"],
    name: l("Kajakken in de mangroves", "Kayaking in the mangroves"),
    art: "nature",
    area: "Lac Bay",
    mapsQuery: "Mangrove Center Bonaire",
    coordinates: { lat: 12.1170, lng: -68.2320, approximate: true },
    tags: ["nature", "family", "active", "book-ahead"],
    summary: l("Peddel door stille kanaaltjes tussen de mangroves van Lac Bay.", "Paddle through quiet channels among the mangroves of Lac Bay."),
    whyWeRecommend: l("Rustig, bijzonder en je ziet jonge vissen tussen de wortels.", "Peaceful, special, and you'll spot young fish among the roots."),
    activity: act({
      why: ["Een kraamkamer van de zee, van dichtbij.", "The ocean's nursery, up close."],
      forWho: ["Iedereen, ook gezinnen.", "Everyone, families included."],
      duration: ["2–3 uur.", "2–3 hours."],
      bring: ["Zwemkleding, pet, water.", "Swimwear, cap, water."],
      bestTime: ["Ochtend.", "Morning."],
      diyOrBook: ["Boeken bij een lokale aanbieder.", "Book with a local provider."],
      keepInMind: ["Gids verplicht of aangeraden — check bij boeking.", "Guide required or recommended — check when booking."],
    }),
    keywords: ["mangroves", "kajak", "kayak", "kajakken", "kayaking", "peddelen", "lac bay"],
  },
  {
    id: "windsurfing",
    demo: true,
    category: "activities",
    name: l("Windsurfen & kitesurfen", "Windsurfing & kitesurfing"),
    art: "wind",
    area: l("Lac Bay & Atlantis", "Lac Bay & Atlantis"),
    mapsQuery: "Lac Bay windsurfing Bonaire",
    coordinates: { lat: 12.1060, lng: -68.2290, approximate: true },
    tags: ["active", "book-ahead"],
    summary: l("Constante wind en ondiep water: Bonaire is een droomplek om te leren of te knallen.", "Steady wind and shallow water: Bonaire is a dream spot to learn or to fly."),
    whyWeRecommend: l("Zelfs als je het nog nooit hebt gedaan: een les in Lac Bay is een ervaring.", "Even if you've never tried: a lesson in Lac Bay is an experience."),
    activity: act({
      why: ["Betrouwbare wind en veilig ondiep water.", "Reliable wind and safe shallow water."],
      forWho: ["Beginners tot gevorderden.", "Beginners to experts."],
      duration: ["Les van enkele uren.", "A lesson of a few hours."],
      bring: ["Rashguard, zonnebrand, water.", "Rash guard, sunscreen, water."],
      bestTime: ["Middag, als de wind aantrekt.", "Afternoon, when the wind picks up."],
      diyOrBook: ["Les en huur boeken bij een surfschool.", "Book lessons and rentals with a surf school."],
      keepInMind: ["Kitesurfen kan alleen op aangewezen plekken — informeer ter plaatse.", "Kitesurfing is only allowed in designated areas — ask locally."],
    }),
    keywords: ["windsurfen", "windsurfing", "kitesurfen", "kitesurfing", "kite", "surf", "les", "lesson", "wind"],
  },
  {
    id: "diving-intro",
    demo: true,
    category: "diving",
    alsoIn: ["activities"],
    name: l("Duiken op Bonaire", "Diving on Bonaire"),
    art: "reef",
    area: l("Hele westkust", "The whole west coast"),
    tags: ["diving", "book-ahead"],
    summary: l("Bonaire is wereldberoemd om het kant-duiken: vanaf de kust het rif op.", "Bonaire is world-famous for shore diving: straight from the coast onto the reef."),
    whyWeRecommend: l("Nog geen brevet? Een introductieduik is een onvergetelijke eerste kennismaking.", "No certification yet? An intro dive is an unforgettable first taste."),
    activity: act({
      why: ["Honderden duikstekken bereikbaar met de auto.", "Hundreds of dive sites reachable by car."],
      forWho: ["Van nieuwsgierige beginners tot ervaren duikers.", "From curious beginners to experienced divers."],
      duration: ["Een ochtend of meerdere dagen.", "A morning or several days."],
      bring: ["Brevet, logboek, rifvriendelijke zonnebrand.", "Certification card, logbook, reef-safe sunscreen."],
      bestTime: ["Ochtend, voor de beste zichtbaarheid en rust.", "Morning, for visibility and calm."],
      diyOrBook: ["Materiaal en cursussen via een lokale duikschool.", "Gear and courses via a local dive school."],
      keepInMind: ["Er geldt een natuurbijdrage voor duikers en snorkelaars — regel die vooraf.", "A nature fee applies to divers and snorkelers — arrange it beforehand."],
    }),
    keywords: ["duiken", "diving", "dive", "padi", "brevet", "duikschool", "dive school", "shore dive", "nature fee", "natuurbijdrage"],
  },
  {
    id: "seru-largu",
    demo: true,
    category: "sunset",
    alsoIn: ["hidden-gems", "nature"],
    name: "Seru Largu",
    art: "sunset",
    area: l("Boven Kralendijk", "Above Kralendijk"),
    mapsQuery: "Seru Largu Bonaire",
    coordinates: { lat: 12.1860, lng: -68.2720, approximate: true },
    tags: ["sunset", "romantic", "nature"],
    summary: l("Uitzichtpunt op een heuvel met een weids panorama over het eiland.", "Hilltop lookout with a sweeping view over the island."),
    whyWeRecommend: l("Weinig mensen, veel uitzicht. Neem iets te drinken mee voor zonsondergang.", "Few people, big views. Bring something to drink for sunset."),
    keywords: ["seru largu", "uitzicht", "view", "lookout", "sunset", "zonsondergang", "heuvel", "hill"],
  },
  {
    id: "willemstoren",
    demo: true,
    category: "roadtrips",
    alsoIn: ["hidden-gems"],
    name: l("Vuurtoren Willemstoren", "Willemstoren Lighthouse"),
    art: "sea",
    area: l("Zuidpunt", "Southern tip"),
    mapsQuery: "Willemstoren Lighthouse Bonaire",
    coordinates: { lat: 12.0260, lng: -68.2380, approximate: true },
    tags: ["worth-the-drive", "nature"],
    summary: l("De oudste vuurtoren van het eiland, met wilde golven aan de zuidpunt.", "The island's oldest lighthouse, with wild surf at the southern tip."),
    whyWeRecommend: l("Een mooie stop op je rondrit door het zuiden.", "A beautiful stop on your drive around the south."),
    keywords: ["vuurtoren", "lighthouse", "willemstoren", "zuiden", "south", "roadtrip"],
  },
  {
    id: "rincon",
    demo: true,
    category: "roadtrips",
    alsoIn: ["rainy-day", "hidden-gems"],
    name: "Rincon",
    art: "town",
    area: l("Noorden", "North"),
    mapsQuery: "Rincon Bonaire",
    coordinates: { lat: 12.2350, lng: -68.3350, approximate: true },
    tags: ["local", "worth-the-drive"],
    summary: l("Het oudste dorp van Bonaire, met kleurrijke huisjes tussen de heuvels.", "Bonaire's oldest village, with colourful houses among the hills."),
    whyWeRecommend: l("Rustig, authentiek en een mooie stop tijdens een rondrit door het noorden.", "Quiet, authentic and a lovely stop on a drive around the north."),
    keywords: ["rincon", "dorp", "village", "lokaal", "local", "noorden", "north", "cultuur", "culture"],
  },
  {
    id: "donkey-sanctuary",
    demo: true,
    category: "kids",
    alsoIn: ["activities", "rainy-day"],
    name: "Donkey Sanctuary Bonaire",
    art: "nature",
    area: l("Richting Lac Bay", "Towards Lac Bay"),
    mapsQuery: "Donkey Sanctuary Bonaire",
    coordinates: { lat: 12.1380, lng: -68.2380, approximate: true },
    tags: ["family"],
    summary: l("Opvang voor ezels waar je doorheen rijdt terwijl nieuwsgierige ezels komen kijken.", "A donkey sanctuary you drive through while curious donkeys come to say hello."),
    whyWeRecommend: l("Kinderen (en volwassenen) vinden het geweldig.", "Kids (and grown-ups) love it."),
    keywords: ["ezels", "donkeys", "donkey", "kinderen", "kids", "dieren", "animals"],
  },
  {
    id: "kralendijk-stroll",
    demo: true,
    category: "rainy-day",
    alsoIn: ["activities"],
    name: l("Kralendijk & de boulevard", "Kralendijk & the waterfront"),
    art: "town",
    area: "Kralendijk",
    mapsQuery: "Kralendijk Bonaire",
    coordinates: { lat: 12.1500, lng: -68.2770, approximate: true },
    tags: ["local", "family"],
    summary: l("Kleurrijke gebouwtjes, winkeltjes, cafés en de zee langs de boulevard.", "Colourful buildings, little shops, cafés and the sea along the boulevard."),
    whyWeRecommend: l("Perfect voor een rustige ochtend of een dag met minder weer.", "Perfect for a slow morning or a day with less sunshine."),
    keywords: ["kralendijk", "centrum", "town", "winkelen", "shopping", "boulevard", "regen", "rain"],
  },
  {
    id: "boat-trip",
    demo: true,
    category: "activities",
    alsoIn: ["snorkeling"],
    name: l("Boottocht & snorkeltrip", "Boat trip & snorkel tour"),
    art: "boat",
    area: l("Vanuit Kralendijk", "From Kralendijk"),
    tags: ["snorkeling", "book-ahead"],
    summary: l("Een dag op het water langs de mooiste riffen — met een tour of met onze eigen boot.", "A day on the water along the best reefs — on a tour or with our own boat."),
    whyWeRecommend: l("Bonaire vanaf het water is een totaal andere ervaring.", "Bonaire from the water is a completely different experience."),
    activity: act({
      why: ["Riffen, Klein Bonaire en de kust vanaf zee.", "Reefs, Klein Bonaire and the coast from the sea."],
      forWho: ["Iedereen.", "Everyone."],
      duration: ["Een halve of hele dag.", "Half a day or a full day."],
      bring: ["Zonnebrand, pet, snorkelset, water.", "Sunscreen, cap, snorkel gear, water."],
      bestTime: ["Ochtend, als de zee het rustigst is.", "Morning, when the sea is calmest."],
      diyOrBook: ["Tour boeken — of vraag naar de boot van Kas Daas.", "Book a tour — or ask about the Kas Daas boat."],
      keepInMind: ["Luister naar de instructies van de kapitein.", "Follow the captain's instructions."],
    }),
    keywords: ["boot", "boat", "boottocht", "boat trip", "tour", "snorkeltrip", "zeilen", "sailing"],
  },
  {
    id: "fishing",
    demo: true,
    category: "activities",
    name: l("Vissen", "Fishing"),
    art: "sea",
    tags: ["book-ahead"],
    summary: l("Diepzeevissen met een lokale kapitein.", "Deep-sea fishing with a local captain."),
    whyWeRecommend: l("Voor wie een dag op zee wil met kans op een grote vangst.", "For anyone who wants a day at sea with a chance of a big catch."),
    tip: l("Het hele rif rond Bonaire is beschermd marine park — vissen alleen via een erkende aanbieder.", "The whole reef around Bonaire is a protected marine park — fish only with a licensed operator."),
    keywords: ["vissen", "fishing", "hengelen", "diepzee", "deep sea"],
  },
  {
    id: "hiking-biking",
    demo: true,
    category: "activities",
    alsoIn: ["nature"],
    name: l("Wandelen & mountainbiken", "Hiking & mountain biking"),
    art: "nature",
    tags: ["active", "nature"],
    summary: l("Routes door cactuslandschap en langs de kust, voor wie actief wil zijn.", "Trails through cactus landscapes and along the coast, for active days."),
    whyWeRecommend: l("Het vroege ochtendlicht op de trails is magisch.", "The early morning light on the trails is magical."),
    activity: act({
      why: ["Stilte, uitzichten en een heel ander Bonaire.", "Silence, views and a whole different Bonaire."],
      forWho: ["Sportieve gasten.", "Active guests."],
      duration: ["1–4 uur.", "1–4 hours."],
      bring: ["Veel water, pet, goede schoenen.", "Plenty of water, a cap, good shoes."],
      bestTime: ["Heel vroeg — vóór de hitte.", "Very early — before the heat."],
      diyOrBook: ["Fietsen huren of een tour boeken.", "Rent bikes or book a tour."],
      keepInMind: ["Het wordt snel heet; ga niet alleen op pad en laat weten waar je bent.", "It gets hot fast; don't go alone and tell someone where you are."],
    }),
    keywords: ["wandelen", "hiking", "hike", "mountainbike", "mtb", "fietsen", "biking", "trail"],
  },
  {
    id: "events-placeholder",
    demo: true,
    category: "activities",
    name: l("[LOKALE EVENEMENTEN INVULLEN]", "[TO FILL IN: LOCAL EVENTS]"),
    art: "night",
    tags: ["local"],
    summary: l("Ruimte voor terugkerende evenementen, markten of feestdagen.", "Space for recurring events, markets or holidays."),
    keywords: ["evenement", "event", "markt", "market", "feest", "festival", "muziek"],
  },
];

export const groceries: Place[] = [
  {
    id: "van-den-tweel",
    demo: true,
    category: "groceries",
    name: "Van den Tweel Supermarket",
    art: "practical",
    area: "Kralendijk",
    mapsQuery: "Van den Tweel Supermarket Bonaire",
    coordinates: { lat: 12.1580, lng: -68.2700, approximate: true },
    tags: [],
    summary: l("Grote supermarkt met een ruim assortiment, ook veel bekende Nederlandse producten.", "Large supermarket with a wide range, including many Dutch products."),
    keywords: ["supermarkt", "supermarket", "boodschappen", "groceries", "winkel", "shop"],
  },
  {
    id: "warehouse",
    demo: true,
    category: "groceries",
    name: "Warehouse Bonaire",
    art: "practical",
    area: "Kralendijk",
    mapsQuery: "Warehouse Bonaire supermarket",
    coordinates: { lat: 12.1440, lng: -68.2680, approximate: true },
    tags: [],
    summary: l("Supermarkt met een groot assortiment, handig voor een eerste grote boodschappenronde.", "Supermarket with a large range, handy for a big first shop."),
    keywords: ["supermarkt", "supermarket", "boodschappen", "groceries", "winkel", "shop"],
  },
];

export const practicalPlaces: Place[] = [
  {
    id: "hospital",
    demo: true,
    category: "practical",
    name: l("Ziekenhuis Fundashon Mariadal", "Hospital Fundashon Mariadal"),
    art: "practical",
    area: "Kralendijk",
    mapsQuery: "Fundashon Mariadal Bonaire",
    coordinates: { lat: 12.1540, lng: -68.2710, approximate: true },
    summary: l("Het ziekenhuis van Bonaire.", "Bonaire's hospital."),
    keywords: ["ziekenhuis", "hospital", "dokter", "doctor", "medisch", "medical", "eerste hulp", "emergency room"],
  },
  {
    id: "airport",
    demo: true,
    category: "practical",
    name: "Flamingo Airport",
    art: "practical",
    area: "Kralendijk",
    mapsQuery: "Flamingo International Airport Bonaire",
    coordinates: { lat: 12.1310, lng: -68.2685, approximate: true },
    summary: l("Het vliegveld van Bonaire.", "Bonaire's airport."),
    keywords: ["vliegveld", "airport", "vlucht", "flight", "luchthaven"],
  },
  {
    id: "pharmacy-placeholder",
    demo: true,
    category: "practical",
    name: l("[APOTHEEK IN DE BUURT INVULLEN]", "[TO FILL IN: NEARBY PHARMACY]"),
    art: "practical",
    summary: l("Plek voor de dichtstbijzijnde apotheek.", "Space for the nearest pharmacy."),
    keywords: ["apotheek", "pharmacy", "medicijnen", "medicine", "drogist"],
  },
  {
    id: "gas-station-placeholder",
    demo: true,
    category: "practical",
    name: l("[TANKSTATION IN DE BUURT INVULLEN]", "[TO FILL IN: NEARBY GAS STATION]"),
    art: "practical",
    summary: l("Plek voor het dichtstbijzijnde tankstation.", "Space for the nearest gas station."),
    keywords: ["tankstation", "gas station", "benzine", "petrol", "tanken", "fuel"],
  },
];
