import { l } from "../_helpers";
import type { Place } from "@/lib/types";

/**
 * ─────────────────────────────────────────────────────────────────────────────
 *  EAT & DRINK
 *  ⚠️ DEMO CONTENT. These entries are examples so the interface can be
 *  reviewed. Names refer to places on Bonaire, but NOTHING has been verified:
 *  check whether each place is still open and whether the description still
 *  fits, then remove `demo: true`. No phone numbers, prices or opening hours
 *  have been filled in on purpose — add them only once verified.
 * ─────────────────────────────────────────────────────────────────────────────
 */
export const food: Place[] = [
  // ── Kas Daas favourites (named by the owner). Addresses, coordinates and
  //    websites looked up online (OpenStreetMap / official sites, Sept 2026).
  //    Descriptions are short and general; the owner may personalise them.
  {
    id: "brass-boer",
    category: "food",
    name: "Brass Boer",
    art: "food",
    mapsQuery: "Brass Boer, Punt Vierkant 44, Kralendijk, Bonaire",
    favorite: true,
    tags: ["favorite", "dinner", "romantic"],
    address: "Punt Vierkant 44 (Delfins Beach Resort), Kralendijk",
    area: "Belnem",
    coordinates: { lat: 12.1153441, lng: -68.2942339 },
    website: "https://www.brassboer.com/bonaire/en/",
    travelTime: l("Op loopafstand — ± 600 m hemelsbreed", "Walking distance — ± 600 m as the crow flies"),
    summary: l(
      "Fine dining van Thérèse en wijlen Jonnie Boer, bekend van De Librije in Zwolle.",
      "Fine dining from Thérèse and the late Jonnie Boer, known for De Librije in Zwolle.",
    ),
    whyWeRecommend: l("Voor die ene bijzondere avond van je vakantie.", "For that one special evening of your holiday."),
    tip: l("Reserveer ruim van tevoren.", "Book well in advance."),
    restaurant: { cuisine: l("Fine dining", "Fine dining"), styles: ["fine-dining"], reservationRecommended: true },
    keywords: ["brass boer", "jonnie boer", "therese boer", "thérèse boer", "librije", "fine dining", "diner", "dinner", "restaurant", "sterrenrestaurant", "romantisch"],
  },
  {
    id: "ingridients",
    category: "food",
    alsoIn: ["sunset"],
    name: "Ingridients",
    art: "sunset",
    area: "Kralendijk (Buddy Dive)",
    mapsQuery: "Ingridients, Buddy Dive Resort, Kralendijk, Bonaire",
    favorite: true,
    tags: ["favorite", "dinner", "waterfront"],
    address: "Kaya Gob. N. Debrot 85 (Buddy Dive Resort), Kralendijk",
    coordinates: { lat: 12.1709627, lng: -68.2877443 },
    website: "https://ingridientsrestaurant.com/",
    summary: l("Restaurant aan het water bij Buddy Dive Resort.", "Waterfront restaurant at Buddy Dive Resort."),
    whyWeRecommend: l("Een van onze favorieten: heerlijk eten met de zee naast je tafel.", "One of our favourites: lovely food with the sea right next to your table."),
    restaurant: { cuisine: l("Internationaal", "International"), styles: ["waterfront", "international"], reservationRecommended: true },
    keywords: ["ingridients", "ingredients", "buddy dive", "diner", "dinner", "restaurant", "waterfront"],
  },
  {
    id: "ocean-oasis",
    category: "food",
    alsoIn: ["drinks", "beaches"],
    name: "Ocean Oasis",
    art: "beach",
    mapsQuery: "Ocean Oasis Beach Club, EEG Boulevard, Kralendijk, Bonaire",
    favorite: true,
    tags: ["favorite", "lunch", "waterfront", "drinks"],
    address: "EEG Boulevard 260, Kralendijk",
    area: "Belnem",
    coordinates: { lat: 12.1100667, lng: -68.2923208 },
    website: "https://www.oceanoasisbonaire.com/",
    travelTime: l("± 1 km hemelsbreed", "± 1 km as the crow flies"),
    summary: l("Beachclub aan zee om te eten, te drinken en te relaxen.", "Beach club by the sea to eat, drink and relax."),
    whyWeRecommend: l("Een van onze favoriete plekken voor een ontspannen middag.", "One of our favourite spots for a relaxed afternoon."),
    restaurant: { cuisine: l("Beachclub", "Beach club"), styles: ["waterfront", "lunch", "casual"], reservationRecommended: null },
    keywords: ["ocean oasis", "beachclub", "beach club", "lunch", "strand", "beach", "drinks", "borrel"],
  },
  {
    id: "sebastians",
    category: "food",
    name: "Sebastian's",
    art: "food",
    area: "Kralendijk",
    mapsQuery: "Sebastian's, J.A. Abraham Boulevard 60, Kralendijk, Bonaire",
    favorite: true,
    tags: ["favorite", "dinner", "waterfront"],
    address: "J.A. Abraham Boulevard 60, Kralendijk",
    coordinates: { lat: 12.1406197, lng: -68.2758352 },
    summary: l("Restaurant aan het water in Kralendijk.", "Waterfront restaurant in Kralendijk."),
    whyWeRecommend: l("Een van onze favoriete adressen voor een fijne avond.", "One of our favourite spots for a lovely evening."),
    restaurant: { cuisine: l("Internationaal", "International"), styles: ["waterfront", "international"], reservationRecommended: true },
    keywords: ["sebastians", "sebastian's", "sebastian", "diner", "dinner", "restaurant"],
  },
  {
    id: "the-dock",
    category: "food",
    alsoIn: ["drinks"],
    name: "The Dock",
    art: "sunset",
    mapsQuery: "The Dock, Kaya International 90, Kralendijk, Bonaire",
    favorite: true,
    tags: ["favorite", "waterfront"],
    address: "Kaya International 90 (Ocean Breeze Boutique Hotel & Marina), Kralendijk",
    area: "Kralendijk",
    coordinates: { lat: 12.1351131, lng: -68.2721149 },
    summary: l("Restaurant met zwembad aan de jachthaven van Ocean Breeze.", "Restaurant with pool at the Ocean Breeze marina."),
    restaurant: { cuisine: l("Eten & drinks", "Food & drinks"), styles: ["waterfront", "casual"], reservationRecommended: null },
    keywords: ["the dock", "dock", "diner", "dinner", "drinks", "borrel", "restaurant"],
  },
  {
    id: "club-tropicana",
    category: "food",
    alsoIn: ["drinks"],
    name: "Club Tropicana",
    art: "night",
    mapsQuery: "Club Tropicana, Delfins Beach Resort, Kralendijk, Bonaire",
    favorite: true,
    tags: ["favorite", "drinks"],
    address: "Punt Vierkant 44 (Delfins Beach Resort), Kralendijk",
    area: "Belnem",
    coordinates: { lat: 12.1150042, lng: -68.2939695 },
    website: "https://tropicana-bonaire.com/club/en/",
    travelTime: l("Op loopafstand — ± 600 m hemelsbreed", "Walking distance — ± 600 m as the crow flies"),
    summary: l("Beach brasserie bij Delfins Beach Resort, vlak bij Kas Daas.", "Beach brasserie at Delfins Beach Resort, close to Kas Daas."),
    restaurant: { cuisine: l("Eten & drinks", "Food & drinks"), styles: ["casual"], reservationRecommended: null },
    keywords: ["club tropicana", "tropicana", "drinks", "borrel", "diner", "dinner"],
  },
  {
    id: "it-rains-fishes",
    category: "food",
    alsoIn: ["sunset"],
    name: "It Rains Fishes",
    art: "food",
    area: "Kralendijk",
    mapsQuery: "It Rains Fishes, Kaya J.N.E. Craane 24, Kralendijk, Bonaire",
    coordinates: { lat: 12.1537296, lng: -68.2782539 },
    favorite: true,
    tags: ["favorite", "dinner", "waterfront", "romantic"],
    address: "Kaya J.N.E. Craane 24, Kralendijk",
    summary: l("Vis en zeevruchten aan de boulevard, met de zee op een paar meter.", "Fish and seafood on the waterfront, with the sea just a few metres away."),
    whyWeRecommend: l(
      "Een klassieker voor een eerste avond: ontspannen sfeer, uitzicht op het water en gerechten met verse vis.",
      "A classic for a first evening: relaxed atmosphere, a view of the water and dishes with fresh fish.",
    ),
    tip: l("Vraag bij reserveren naar een tafel aan de waterkant.", "Ask for a table by the water when you book."),
    restaurant: { cuisine: l("Vis & internationaal", "Seafood & international"), styles: ["fish", "waterfront", "international"], reservationRecommended: true },
    keywords: ["vis", "fish", "seafood", "zeevruchten", "diner", "dinner", "restaurant"],
  },
  {
    id: "karels-beach-bar",
    category: "drinks",
    alsoIn: ["sunset", "food"],
    name: "Karel's Beach Bar",
    art: "sunset",
    area: "Kralendijk",
    mapsQuery: "Karel's Beach Bar, Kaya J.N.E. Craane 12, Kralendijk, Bonaire",
    coordinates: { lat: 12.1517678, lng: -68.2778203 },
    tags: ["sunset", "drinks", "waterfront"],
    address: "Kaya J.N.E. Craane 12, Kralendijk",
    summary: l("Een drankje op een pier boven het water, precies op tijd voor de zonsondergang.", "A drink on a pier over the water, just in time for sunset."),
    whyWeRecommend: l(
      "Hier kijk je de zon letterlijk de zee in. Ideaal om de dag af te sluiten voor het diner.",
      "Watch the sun sink right into the sea. The perfect way to end the day before dinner.",
    ),
    tip: l("Kom een half uur voor zonsondergang voor de mooiste plekjes.", "Arrive half an hour before sunset for the best seats."),
    restaurant: { cuisine: l("Bar & snacks", "Bar & bites"), styles: ["waterfront", "sunset", "casual"], reservationRecommended: null },
    keywords: ["bar", "drinks", "borrel", "cocktail", "sunset", "zonsondergang", "bier", "beer"],
  },
  {
    id: "bobbejans",
    demo: true,
    category: "food",
    name: "Bobbejan's",
    art: "food",
    area: "Kralendijk",
    mapsQuery: "Bobbejan's Take Away Bonaire",
    coordinates: { lat: 12.1455, lng: -68.2718, approximate: true },
    tags: ["local", "dinner", "quick-bite"],
    summary: l("Een lokale favoriet voor ribs en saté, ongedwongen en gezellig.", "A local favourite for ribs and satay, casual and friendly."),
    whyWeRecommend: l("Geen poespas, wel heel veel smaak. Echt eilandgevoel.", "No frills, lots of flavour. Real island feel."),
    tip: l("Openingsdagen zijn beperkt — controleer ze vooraf.", "Opening days are limited — check before you go."),
    restaurant: { cuisine: l("BBQ & lokaal", "BBQ & local"), styles: ["meat", "local", "casual", "takeaway"], reservationRecommended: false },
    keywords: ["ribs", "bbq", "saté", "satay", "vlees", "meat", "lokaal", "local", "afhalen", "takeaway"],
  },
  {
    id: "capriccio",
    demo: true,
    category: "food",
    name: "Capriccio",
    art: "food",
    area: "Kralendijk",
    mapsQuery: "Capriccio Bonaire",
    coordinates: { lat: 12.1532, lng: -68.2780, approximate: true },
    tags: ["dinner", "romantic"],
    summary: l("Italiaans restaurant met huisgemaakte pasta en pizza.", "Italian restaurant with homemade pasta and pizza."),
    whyWeRecommend: l("Voor de avond dat je zin hebt in een goede pizza of pasta en een fijn glas wijn.", "For the evening you're craving a proper pizza or pasta and a good glass of wine."),
    restaurant: { cuisine: l("Italiaans", "Italian"), styles: ["international", "fine-dining"], reservationRecommended: true },
    keywords: ["italiaans", "italian", "pizza", "pasta", "wijn", "wine", "diner"],
  },
  {
    id: "between-2-buns",
    demo: true,
    category: "food",
    name: "Between 2 Buns",
    art: "coffee",
    area: "Kralendijk",
    mapsQuery: "Between 2 Buns Bonaire",
    coordinates: { lat: 12.1487, lng: -68.2757, approximate: true },
    tags: ["lunch", "quick-bite"],
    summary: l("Broodjes en lunch in het centrum — snel, vers en lekker.", "Sandwiches and lunch in town — quick, fresh and tasty."),
    whyWeRecommend: l("Handig tussen twee duiken of een ochtend in Kralendijk door.", "Perfect between two dives or during a morning in Kralendijk."),
    restaurant: { cuisine: l("Broodjes & lunch", "Sandwiches & lunch"), styles: ["lunch", "casual", "takeaway"], reservationRecommended: false },
    keywords: ["lunch", "broodje", "sandwich", "snel", "quick", "afhalen"],
  },
  {
    id: "cuba-compagnie",
    demo: true,
    category: "food",
    alsoIn: ["drinks"],
    name: "Cuba Compagnie",
    art: "night",
    area: "Kralendijk",
    mapsQuery: "Cuba Compagnie Bonaire",
    coordinates: { lat: 12.1505, lng: -68.2770, approximate: true },
    tags: ["dinner", "drinks"],
    summary: l("Levendige plek in het centrum voor diner en cocktails.", "Lively spot in town for dinner and cocktails."),
    whyWeRecommend: l("Leuk als je na het eten nog even wilt blijven hangen met een cocktail.", "Great if you feel like lingering over a cocktail after dinner."),
    restaurant: { cuisine: l("Latijns-Amerikaans geïnspireerd", "Latin-inspired"), styles: ["international", "casual"], reservationRecommended: null },
    keywords: ["cocktail", "diner", "dinner", "cuba", "muziek", "music", "uitgaan", "nightlife"],
  },
  {
    id: "la-cantina",
    demo: true,
    category: "drinks",
    alsoIn: ["food"],
    name: "La Cantina Cerveceria",
    art: "night",
    area: "Kralendijk",
    mapsQuery: "La Cantina Cerveceria Bonaire",
    coordinates: { lat: 12.1480, lng: -68.2745, approximate: true },
    tags: ["drinks", "dinner", "local"],
    summary: l("Brouwerij met eigen bieren en ongedwongen eten.", "Brewery with its own beers and casual food."),
    whyWeRecommend: l("Een lokaal gebrouwen biertje na een dag in de zon — wat wil je nog meer?", "A locally brewed beer after a day in the sun — what more do you need?"),
    restaurant: { cuisine: l("Brouwerij & grill", "Brewery & grill"), styles: ["casual", "meat"], reservationRecommended: null },
    keywords: ["bier", "beer", "brouwerij", "brewery", "borrel", "burger"],
  },
  {
    id: "jibe-city",
    demo: true,
    category: "food",
    alsoIn: ["drinks", "beaches"],
    name: "Jibe City",
    art: "wind",
    area: "Lac Bay / Sorobon",
    mapsQuery: "Jibe City Bonaire",
    coordinates: { lat: 12.1073, lng: -68.2276, approximate: true },
    tags: ["lunch", "waterfront", "after-the-beach"],
    summary: l("Strandbar aan Lac Bay, midden tussen de windsurfers.", "Beach bar on Lac Bay, right among the windsurfers."),
    whyWeRecommend: l("Lunch met je voeten in het zand en uitzicht op het ondiepe, turquoise water.", "Lunch with your toes in the sand and a view of the shallow turquoise bay."),
    restaurant: { cuisine: l("Strandlunch", "Beach lunch"), styles: ["lunch", "waterfront", "casual"], reservationRecommended: false },
    keywords: ["lac bay", "sorobon", "windsurf", "strand", "beach", "lunch", "bar"],
  },
  {
    id: "gelato",
    demo: true,
    category: "snacks",
    alsoIn: ["kids"],
    name: "Gio's Gelateria",
    art: "town",
    area: "Kralendijk",
    mapsQuery: "Gio's Gelateria Bonaire",
    coordinates: { lat: 12.1510, lng: -68.2775, approximate: true },
    tags: ["family", "quick-bite"],
    summary: l("Italiaans schepijs in het centrum van Kralendijk.", "Italian gelato in the centre of Kralendijk."),
    whyWeRecommend: l("De perfecte afsluiter van een wandeling over de boulevard.", "The perfect end to a stroll along the waterfront."),
    keywords: ["ijs", "ice cream", "gelato", "dessert", "kinderen", "kids"],
  },
  {
    id: "rum-runners",
    category: "food",
    alsoIn: ["sunset"],
    name: "Rum Runners",
    art: "sunset",
    area: "Kralendijk (Captain Don's Habitat)",
    mapsQuery: "Rum Runners, Captain Don's Habitat, Kralendijk, Bonaire",
    coordinates: { lat: 12.1722082, lng: -68.2882016 },
    favorite: true,
    tags: ["favorite", "dinner", "sunset", "waterfront"],
    address: "Kaya Gob. N. Debrot 103 (Captain Don's Habitat), Kralendijk",
    website: "https://www.habitatbonaire.com/dining",
    summary: l("Restaurant aan het water bij een bekend duikresort, ideaal bij zonsondergang.", "Waterfront restaurant at a well-known dive resort, lovely at sunset."),
    whyWeRecommend: l("Ontspannen diner met de zee als decor.", "A relaxed dinner with the sea as your backdrop."),
    restaurant: { cuisine: l("Internationaal", "International"), styles: ["waterfront", "sunset", "international"], reservationRecommended: true },
    keywords: ["diner", "dinner", "sunset", "zee", "sea", "waterfront"],
  },
  {
    id: "coffee-placeholder",
    demo: true,
    category: "breakfast",
    name: l("[ONTBIJTZAAK INVULLEN]", "[TO FILL IN: BREAKFAST SPOT]"),
    art: "coffee",
    tags: ["breakfast"],
    summary: l("Plek voor jullie favoriete ontbijtadres en de beste koffie van het eiland.", "Space for your favourite breakfast spot and the best coffee on the island."),
    restaurant: { cuisine: l("Ontbijt & koffie", "Breakfast & coffee"), styles: ["breakfast"], reservationRecommended: null },
    keywords: ["ontbijt", "breakfast", "koffie", "coffee", "cappuccino", "brunch"],
  },
  {
    id: "foodtruck-placeholder",
    demo: true,
    category: "food",
    name: l("[FOODTRUCK INVULLEN]", "[TO FILL IN: FOOD TRUCK]"),
    art: "food",
    tags: ["local", "quick-bite"],
    summary: l("Plek voor een lokale foodtruck die jullie aanraden.", "Space for a local food truck you recommend."),
    restaurant: { cuisine: l("Lokaal", "Local"), styles: ["foodtruck", "local", "takeaway"], reservationRecommended: false },
    keywords: ["foodtruck", "food truck", "lokaal", "local", "snack", "pizza"],
  },
];
