import { l } from "../_helpers";
import type { Place } from "@/lib/types";

/**
 * ─────────────────────────────────────────────────────────────────────────────
 *  EAT & DRINK
 *  ⚠️ DEMO CONTENT. These entries are examples so the interface can be
 *  reviewed. Names refer to places on Bonaire, but NOTHING has been verified:
 *  check whether each place is still open and whether the description still
 *  fits, then remove `demo: true`. No phone numbers, prices or opening hours
 *  have been filled in on purpose — add them only once verified.
 * ─────────────────────────────────────────────────────────────────────────────
 */
export const food: Place[] = [
  // ── Kas Daas favourites (named by the owner). Addresses, coordinates and
  //    websites looked up online (OpenStreetMap / official sites, Sept 2026).
  //    Descriptions are short and general; the owner may personalise them.
  {
    id: "brass-boer",
    category: "food",
    name: "Brass Boer",
    art: "food",
    mapsQuery: "Brass Boer, Punt Vierkant 44, Kralendijk, Bonaire",
    favorite: true,
    tags: ["favorite", "dinner", "romantic"],
    address: "Punt Vierkant 44 (Delfins Beach Resort), Kralendijk",
    area: "Belnem",
    coordinates: { lat: 12.1153441, lng: -68.2942339 },
    website: "https://www.brassboer.com/bonaire/en/",
    travelTime: l("Op loopafstand — ± 600 m hemelsbreed", "Walking distance — ± 600 m as the crow flies", "A poca distancia a pie: ± 600 m en línea recta"),
    phone: "+599 715 5050",
    reservationUrl: "https://www.brassboer.com/bonaire/en/reservations/",
    summary: l(
      "Fine dining van Thérèse en wijlen Jonnie Boer, bekend van De Librije in Zwolle.",
      "Fine dining from Thérèse and the late Jonnie Boer, known for De Librije in Zwolle.", "Alta cocina de Thérèse y el difunto Jonnie Boer, conocidos por De Librije en Zwolle.",
    ),
    whyWeRecommend: l("Voor die ene bijzondere avond van je vakantie.", "For that one special evening of your holiday.", "Para esa noche especial de tus vacaciones."),
    tip: l("Reserveer ruim van tevoren.", "Book well in advance.", "Reserva con mucha antelación."),
    restaurant: { cuisine: l("Fine dining", "Fine dining", "Alta cocina"), styles: ["fine-dining"], reservationRecommended: true },
    keywords: ["brass boer", "jonnie boer", "therese boer", "thérèse boer", "librije", "fine dining", "diner", "dinner", "restaurant", "sterrenrestaurant", "romantisch", "cena", "cenar"],
  },
  {
    id: "ingridients",
    category: "food",
    alsoIn: ["sunset"],
    name: "Ingridients",
    art: "sunset",
    area: "Kralendijk (Buddy Dive)",
    mapsQuery: "Ingridients, Buddy Dive Resort, Kralendijk, Bonaire",
    favorite: true,
    tags: ["favorite", "dinner", "waterfront"],
    address: "Kaya Gob. N. Debrot 85 (Buddy Dive Resort), Kralendijk",
    coordinates: { lat: 12.1709627, lng: -68.2877443 },
    website: "https://ingridientsrestaurant.com/",
    reservationUrl: "https://ingridientsrestaurant.com/reservation/",
    summary: l("Restaurant aan het water bij Buddy Dive Resort.", "Waterfront restaurant at Buddy Dive Resort.", "Restaurante junto al mar en Buddy Dive Resort."),
    whyWeRecommend: l("Een van onze favorieten: heerlijk eten met de zee naast je tafel.", "One of our favourites: lovely food with the sea right next to your table.", "Uno de nuestros favoritos: comida deliciosa con el mar junto a tu mesa."),
    restaurant: { cuisine: l("Internationaal", "International", "Internacional"), styles: ["waterfront", "international"], reservationRecommended: true },
    keywords: ["ingridients", "ingredients", "buddy dive", "diner", "dinner", "restaurant", "waterfront", "cena", "cenar"],
  },
  {
    id: "ocean-oasis",
    category: "food",
    alsoIn: ["drinks", "beaches"],
    name: "Ocean Oasis",
    art: "beach",
    mapsQuery: "Ocean Oasis Beach Club, EEG Boulevard, Kralendijk, Bonaire",
    favorite: true,
    tags: ["favorite", "lunch", "waterfront", "drinks"],
    address: "EEG Boulevard 260, Kralendijk",
    area: "Belnem",
    coordinates: { lat: 12.1100667, lng: -68.2923208 },
    website: "https://www.oceanoasisbonaire.com/",
    travelTime: l("± 1 km hemelsbreed", "± 1 km as the crow flies", "± 1 km en línea recta"),
    phone: "+599 701 4440",
    reservationUrl: "https://bookings.zenchef.com/results?rid=386002",
    summary: l("Beachclub aan zee om te eten, te drinken en te relaxen.", "Beach club by the sea to eat, drink and relax.", "Beach club junto al mar para comer, beber y relajarse."),
    whyWeRecommend: l("Een van onze favoriete plekken voor een ontspannen middag.", "One of our favourite spots for a relaxed afternoon.", "Uno de nuestros lugares favoritos para una tarde tranquila."),
    restaurant: { cuisine: l("Beachclub", "Beach club", "Beach club"), styles: ["waterfront", "lunch", "casual"], reservationRecommended: null },
    keywords: ["ocean oasis", "beachclub", "beach club", "lunch", "strand", "beach", "drinks", "borrel", "almuerzo", "playa", "copas", "bebidas"],
  },
  {
    id: "sebastians",
    category: "food",
    name: "Sebastian's",
    art: "food",
    area: "Kralendijk",
    mapsQuery: "Sebastian's, J.A. Abraham Boulevard 60, Kralendijk, Bonaire",
    favorite: true,
    tags: ["favorite", "dinner", "waterfront"],
    address: "J.A. Abraham Boulevard 60, Kralendijk",
    coordinates: { lat: 12.1406197, lng: -68.2758352 },
    phone: "+599 717 1697",
    website: "https://sebastiansrestaurantbonaire.com/residence/",
    summary: l("Restaurant aan het water in Kralendijk.", "Waterfront restaurant in Kralendijk.", "Restaurante junto al mar en Kralendijk."),
    whyWeRecommend: l("Een van onze favoriete adressen voor een fijne avond.", "One of our favourite spots for a lovely evening.", "Uno de nuestros lugares favoritos para una noche agradable."),
    restaurant: { cuisine: l("Internationaal", "International", "Internacional"), styles: ["waterfront", "international"], reservationRecommended: true },
    keywords: ["sebastians", "sebastian's", "sebastian", "diner", "dinner", "restaurant", "cena", "cenar"],
  },
  {
    id: "the-dock",
    category: "food",
    alsoIn: ["drinks"],
    name: "The Dock",
    art: "sunset",
    mapsQuery: "The Dock, Kaya International 90, Kralendijk, Bonaire",
    favorite: true,
    tags: ["favorite", "waterfront"],
    address: "Kaya International 90 (Ocean Breeze Boutique Hotel & Marina), Kralendijk",
    area: "Kralendijk",
    coordinates: { lat: 12.1351131, lng: -68.2721149 },
    phone: "+599 701 2998",
    website: "https://www.thedockbonaire.com/",
    reservationUrl: "https://wa.me/5997012998", // The Dock takes reservations via WhatsApp
    summary: l("Restaurant met zwembad aan de jachthaven van Ocean Breeze.", "Restaurant with pool at the Ocean Breeze marina.", "Restaurante con piscina en el puerto deportivo Ocean Breeze."),
    restaurant: { cuisine: l("Eten & drinks", "Food & drinks", "Comida y bebida"), styles: ["waterfront", "casual"], reservationRecommended: null },
    keywords: ["the dock", "dock", "diner", "dinner", "drinks", "borrel", "restaurant", "cena", "cenar", "copas", "bebidas"],
  },
  {
    id: "club-tropicana",
    category: "food",
    alsoIn: ["drinks"],
    name: "Club Tropicana",
    art: "night",
    mapsQuery: "Club Tropicana, Delfins Beach Resort, Kralendijk, Bonaire",
    favorite: true,
    tags: ["favorite", "drinks"],
    address: "Punt Vierkant 44 (Delfins Beach Resort), Kralendijk",
    area: "Belnem",
    coordinates: { lat: 12.1150042, lng: -68.2939695 },
    website: "https://tropicana-bonaire.com/club/en/",
    travelTime: l("Op loopafstand — ± 600 m hemelsbreed", "Walking distance — ± 600 m as the crow flies", "A poca distancia a pie: ± 600 m en línea recta"),
    phone: "+599 715 5050",
    tip: l("Reserveren is niet nodig — loop gewoon binnen.", "No reservation needed — just walk in.", "No hace falta reservar: simplemente entra."),
    summary: l("Beach brasserie bij Delfins Beach Resort, vlak bij Kas Daas.", "Beach brasserie at Delfins Beach Resort, close to Kas Daas.", "Brasserie de playa en Delfins Beach Resort, cerca de Kas Daas."),
    restaurant: { cuisine: l("Eten & drinks", "Food & drinks", "Comida y bebida"), styles: ["casual"], reservationRecommended: false },
    keywords: ["club tropicana", "tropicana", "drinks", "borrel", "diner", "dinner", "copas", "bebidas", "cena", "cenar"],
  },
  {
    id: "it-rains-fishes",
    category: "food",
    alsoIn: ["sunset"],
    name: "It Rains Fishes",
    art: "food",
    area: "Kralendijk",
    mapsQuery: "It Rains Fishes, Kaya J.N.E. Craane 24, Kralendijk, Bonaire",
    coordinates: { lat: 12.1537296, lng: -68.2782539 },
    favorite: true,
    tags: ["favorite", "dinner", "waterfront", "romantic"],
    address: "Kaya J.N.E. Craane 24, Kralendijk",
    phone: "+599 717 8780",
    website: "https://itrainsfishesbonaire.com/",
    reservationUrl: "https://itrainsfishesbonaire.com/reservations/",
    summary: l("Vis en zeevruchten aan de boulevard, met de zee op een paar meter.", "Fish and seafood on the waterfront, with the sea just a few metres away.", "Pescado y marisco junto al mar, a pocos metros del agua."),
    whyWeRecommend: l(
      "Een klassieker voor een eerste avond: ontspannen sfeer, uitzicht op het water en gerechten met verse vis.",
      "A classic for a first evening: relaxed atmosphere, a view of the water and dishes with fresh fish.", "Un clásico para la primera noche: ambiente relajado, vistas al agua y platos con pescado fresco.",
    ),
    tip: l("Vraag bij reserveren naar een tafel aan de waterkant.", "Ask for a table by the water when you book.", "Pide una mesa junto al agua al reservar."),
    restaurant: { cuisine: l("Vis & internationaal", "Seafood & international", "Pescado, marisco e internacional"), styles: ["fish", "waterfront", "international"], reservationRecommended: true },
    keywords: ["vis", "fish", "seafood", "zeevruchten", "diner", "dinner", "restaurant", "pescado", "marisco", "cena", "cenar"],
  },
  {
    id: "karels-beach-bar",
    category: "drinks",
    alsoIn: ["sunset", "food"],
    name: "Karel's Beach Bar",
    art: "sunset",
    area: "Kralendijk",
    mapsQuery: "Karel's Beach Bar, Kaya J.N.E. Craane 12, Kralendijk, Bonaire",
    coordinates: { lat: 12.1517678, lng: -68.2778203 },
    tags: ["sunset", "drinks", "waterfront"],
    address: "Kaya J.N.E. Craane 12, Kralendijk",
    phone: "+599 717 8434",
    website: "https://www.karelsbeachbar.com/",
    summary: l("Een drankje op een pier boven het water, precies op tijd voor de zonsondergang.", "A drink on a pier over the water, just in time for sunset.", "Una copa en un muelle sobre el agua, justo a tiempo para el atardecer."),
    whyWeRecommend: l(
      "Hier kijk je de zon letterlijk de zee in. Ideaal om de dag af te sluiten voor het diner.",
      "Watch the sun sink right into the sea. The perfect way to end the day before dinner.", "Mira cómo el sol se hunde en el mar. La manera perfecta de acabar el día antes de cenar.",
    ),
    tip: l("Kom een half uur voor zonsondergang voor de mooiste plekjes.", "Arrive half an hour before sunset for the best seats.", "Llega media hora antes del atardecer para conseguir los mejores sitios."),
    restaurant: { cuisine: l("Bar & snacks", "Bar & bites", "Bar y picoteo"), styles: ["waterfront", "sunset", "casual"], reservationRecommended: null },
    keywords: ["bar", "drinks", "borrel", "cocktail", "sunset", "zonsondergang", "bier", "beer", "copas", "bebidas", "atardecer", "puesta de sol", "cerveza"],
  },
  {
    id: "bobbejans",
    demo: true,
    category: "food",
    name: "Bobbejan's",
    art: "food",
    area: "Kralendijk",
    mapsQuery: "Bobbejan's Take Away Bonaire",
    coordinates: { lat: 12.1455, lng: -68.2718, approximate: true },
    tags: ["local", "dinner", "quick-bite"],
    summary: l("Een lokale favoriet voor ribs en saté, ongedwongen en gezellig.", "A local favourite for ribs and satay, casual and friendly.", "Un favorito local para costillas y satay, informal y acogedor."),
    whyWeRecommend: l("Geen poespas, wel heel veel smaak. Echt eilandgevoel.", "No frills, lots of flavour. Real island feel.", "Sin florituras, mucho sabor. Auténtico ambiente isleño."),
    tip: l("Openingsdagen zijn beperkt — controleer ze vooraf.", "Opening days are limited — check before you go.", "Abre pocos días: compruébalo antes de ir."),
    restaurant: { cuisine: l("BBQ & lokaal", "BBQ & local", "Barbacoa y cocina local"), styles: ["meat", "local", "casual", "takeaway"], reservationRecommended: false },
    keywords: ["ribs", "bbq", "saté", "satay", "vlees", "meat", "lokaal", "local", "afhalen", "takeaway", "carne", "para llevar"],
  },
  {
    id: "capriccio",
    demo: true,
    category: "food",
    name: "Capriccio",
    art: "food",
    area: "Kralendijk",
    mapsQuery: "Capriccio Bonaire",
    coordinates: { lat: 12.1532, lng: -68.2780, approximate: true },
    tags: ["dinner", "romantic"],
    summary: l("Italiaans restaurant met huisgemaakte pasta en pizza.", "Italian restaurant with homemade pasta and pizza.", "Restaurante italiano con pasta y pizza caseras."),
    whyWeRecommend: l("Voor de avond dat je zin hebt in een goede pizza of pasta en een fijn glas wijn.", "For the evening you're craving a proper pizza or pasta and a good glass of wine.", "Para la noche en que te apetezca una buena pizza o pasta y una buena copa de vino."),
    restaurant: { cuisine: l("Italiaans", "Italian", "Italiano"), styles: ["international", "fine-dining"], reservationRecommended: true },
    keywords: ["italiaans", "italian", "pizza", "pasta", "wijn", "wine", "diner", "italiano", "vino"],
  },
  {
    id: "between-2-buns",
    demo: true,
    category: "food",
    name: "Between 2 Buns",
    art: "coffee",
    area: "Kralendijk",
    mapsQuery: "Between 2 Buns Bonaire",
    coordinates: { lat: 12.1487, lng: -68.2757, approximate: true },
    tags: ["lunch", "quick-bite"],
    summary: l("Broodjes en lunch in het centrum — snel, vers en lekker.", "Sandwiches and lunch in town — quick, fresh and tasty.", "Bocadillos y almuerzo en el centro: rápido, fresco y rico."),
    whyWeRecommend: l("Handig tussen twee duiken of een ochtend in Kralendijk door.", "Perfect between two dives or during a morning in Kralendijk.", "Perfecto entre dos inmersiones o durante una mañana en Kralendijk."),
    restaurant: { cuisine: l("Broodjes & lunch", "Sandwiches & lunch", "Bocadillos y almuerzo"), styles: ["lunch", "casual", "takeaway"], reservationRecommended: false },
    keywords: ["lunch", "broodje", "sandwich", "snel", "quick", "afhalen", "almuerzo", "bocadillo", "rápido"],
  },
  {
    id: "cuba-compagnie",
    demo: true,
    category: "food",
    alsoIn: ["drinks"],
    name: "Cuba Compagnie",
    art: "night",
    area: "Kralendijk",
    mapsQuery: "Cuba Compagnie Bonaire",
    coordinates: { lat: 12.1505, lng: -68.2770, approximate: true },
    tags: ["dinner", "drinks"],
    summary: l("Levendige plek in het centrum voor diner en cocktails.", "Lively spot in town for dinner and cocktails.", "Local animado en el centro para cenar y tomar cócteles."),
    whyWeRecommend: l("Leuk als je na het eten nog even wilt blijven hangen met een cocktail.", "Great if you feel like lingering over a cocktail after dinner.", "Ideal si te apetece alargar la noche con un cóctel después de cenar."),
    restaurant: { cuisine: l("Latijns-Amerikaans geïnspireerd", "Latin-inspired", "De inspiración latina"), styles: ["international", "casual"], reservationRecommended: null },
    keywords: ["cocktail", "diner", "dinner", "cuba", "muziek", "music", "uitgaan", "nightlife", "cena", "cenar", "música", "vida nocturna"],
  },
  {
    id: "la-cantina",
    demo: true,
    category: "drinks",
    alsoIn: ["food"],
    name: "La Cantina Cerveceria",
    art: "night",
    area: "Kralendijk",
    mapsQuery: "La Cantina Cerveceria Bonaire",
    coordinates: { lat: 12.1480, lng: -68.2745, approximate: true },
    tags: ["drinks", "dinner", "local"],
    summary: l("Brouwerij met eigen bieren en ongedwongen eten.", "Brewery with its own beers and casual food.", "Cervecería con cervezas propias y comida informal."),
    whyWeRecommend: l("Een lokaal gebrouwen biertje na een dag in de zon — wat wil je nog meer?", "A locally brewed beer after a day in the sun — what more do you need?", "Una cerveza local después de un día al sol: ¿qué más se puede pedir?"),
    restaurant: { cuisine: l("Brouwerij & grill", "Brewery & grill", "Cervecería y parrilla"), styles: ["casual", "meat"], reservationRecommended: null },
    keywords: ["bier", "beer", "brouwerij", "brewery", "borrel", "burger", "cerveza", "cervecería"],
  },
  {
    id: "jibe-city",
    demo: true,
    category: "food",
    alsoIn: ["drinks", "beaches"],
    name: "Jibe City",
    art: "wind",
    area: "Lac Bay / Sorobon",
    mapsQuery: "Jibe City Bonaire",
    coordinates: { lat: 12.1073, lng: -68.2276, approximate: true },
    tags: ["lunch", "waterfront", "after-the-beach"],
    summary: l("Strandbar aan Lac Bay, midden tussen de windsurfers.", "Beach bar on Lac Bay, right among the windsurfers.", "Chiringuito en Lac Bay, justo entre los windsurfistas."),
    whyWeRecommend: l("Lunch met je voeten in het zand en uitzicht op het ondiepe, turquoise water.", "Lunch with your toes in the sand and a view of the shallow turquoise bay.", "Almuerzo con los pies en la arena y vistas a la bahía turquesa."),
    restaurant: { cuisine: l("Strandlunch", "Beach lunch", "Almuerzo en la playa"), styles: ["lunch", "waterfront", "casual"], reservationRecommended: false },
    keywords: ["lac bay", "sorobon", "windsurf", "strand", "beach", "lunch", "bar", "playa", "almuerzo"],
  },
  {
    id: "gelato",
    demo: true,
    category: "snacks",
    alsoIn: ["kids"],
    name: "Gio's Gelateria",
    art: "town",
    area: "Kralendijk",
    mapsQuery: "Gio's Gelateria Bonaire",
    coordinates: { lat: 12.1510, lng: -68.2775, approximate: true },
    tags: ["family", "quick-bite"],
    summary: l("Italiaans schepijs in het centrum van Kralendijk.", "Italian gelato in the centre of Kralendijk.", "Helado italiano en el centro de Kralendijk."),
    whyWeRecommend: l("De perfecte afsluiter van een wandeling over de boulevard.", "The perfect end to a stroll along the waterfront.", "El final perfecto para un paseo junto al mar."),
    keywords: ["ijs", "ice cream", "gelato", "dessert", "kinderen", "kids", "helado", "niños"],
  },
  {
    id: "rum-runners",
    category: "food",
    alsoIn: ["sunset"],
    name: "Rum Runners",
    art: "sunset",
    area: "Kralendijk (Captain Don's Habitat)",
    mapsQuery: "Rum Runners, Captain Don's Habitat, Kralendijk, Bonaire",
    coordinates: { lat: 12.1722082, lng: -68.2882016 },
    favorite: true,
    tags: ["favorite", "dinner", "sunset", "waterfront"],
    address: "Kaya Gob. N. Debrot 103 (Captain Don's Habitat), Kralendijk",
    website: "https://www.habitatbonaire.com/dining",
    phone: "+599 717 8290",
    summary: l("Restaurant aan het water bij een bekend duikresort, ideaal bij zonsondergang.", "Waterfront restaurant at a well-known dive resort, lovely at sunset.", "Restaurante junto al mar en un conocido resort de buceo, precioso al atardecer."),
    whyWeRecommend: l("Ontspannen diner met de zee als decor.", "A relaxed dinner with the sea as your backdrop.", "Una cena tranquila con el mar de fondo."),
    restaurant: { cuisine: l("Internationaal", "International", "Internacional"), styles: ["waterfront", "sunset", "international"], reservationRecommended: true },
    keywords: ["diner", "dinner", "sunset", "zee", "sea", "waterfront", "cena", "cenar", "atardecer", "puesta de sol", "mar"],
  },
  {
    id: "coffee-placeholder",
    demo: true,
    category: "breakfast",
    name: l("[ONTBIJTZAAK INVULLEN]", "[TO FILL IN: BREAKFAST SPOT]", "[POR COMPLETAR: SITIO PARA DESAYUNAR]"),
    art: "coffee",
    tags: ["breakfast"],
    summary: l("Plek voor jullie favoriete ontbijtadres en de beste koffie van het eiland.", "Space for your favourite breakfast spot and the best coffee on the island.", "Espacio para tu sitio favorito para desayunar y el mejor café de la isla."),
    restaurant: { cuisine: l("Ontbijt & koffie", "Breakfast & coffee", "Desayuno y café"), styles: ["breakfast"], reservationRecommended: null },
    keywords: ["ontbijt", "breakfast", "koffie", "coffee", "cappuccino", "brunch", "desayuno", "café"],
  },
  {
    id: "foodtruck-placeholder",
    demo: true,
    category: "food",
    name: l("[FOODTRUCK INVULLEN]", "[TO FILL IN: FOOD TRUCK]", "[POR COMPLETAR: FOOD TRUCK]"),
    art: "food",
    tags: ["local", "quick-bite"],
    summary: l("Plek voor een lokale foodtruck die jullie aanraden.", "Space for a local food truck you recommend.", "Espacio para un food truck local que recomiendes."),
    restaurant: { cuisine: l("Lokaal", "Local", "Local"), styles: ["foodtruck", "local", "takeaway"], reservationRecommended: false },
    keywords: ["foodtruck", "food truck", "lokaal", "local", "snack", "pizza"],
  },
];
