import { l } from "../_helpers";
import type { Place } from "@/lib/types";

/**
 * ─────────────────────────────────────────────────────────────────────────────
 *  EAT & DRINK
 *  ⚠️ DEMO CONTENT. These entries are examples so the interface can be
 *  reviewed. Names refer to places on Bonaire, but NOTHING has been verified:
 *  check whether each place is still open and whether the description still
 *  fits, then remove `demo: true`. No phone numbers, prices or opening hours
 *  have been filled in on purpose — add them only once verified.
 * ─────────────────────────────────────────────────────────────────────────────
 */
export const food: Place[] = [
  {
    id: "it-rains-fishes",
    demo: true,
    category: "food",
    alsoIn: ["sunset"],
    name: "It Rains Fishes",
    art: "food",
    area: "Kralendijk",
    mapsQuery: "It Rains Fishes Bonaire",
    coordinates: { lat: 12.1496, lng: -68.2771, approximate: true },
    favorite: true,
    tags: ["favorite", "dinner", "waterfront", "romantic"],
    summary: l("Vis en zeevruchten aan de boulevard, met de zee op een paar meter.", "Fish and seafood on the waterfront, with the sea just a few metres away."),
    whyWeRecommend: l(
      "Een klassieker voor een eerste avond: ontspannen sfeer, uitzicht op het water en gerechten met verse vis.",
      "A classic for a first evening: relaxed atmosphere, a view of the water and dishes with fresh fish.",
    ),
    tip: l("Vraag bij reserveren naar een tafel aan de waterkant.", "Ask for a table by the water when you book."),
    restaurant: { cuisine: l("Vis & internationaal", "Seafood & international"), styles: ["fish", "waterfront", "international"], reservationRecommended: true },
    keywords: ["vis", "fish", "seafood", "zeevruchten", "diner", "dinner", "restaurant"],
  },
  {
    id: "karels-beach-bar",
    demo: true,
    category: "drinks",
    alsoIn: ["sunset", "food"],
    name: "Karel's Beach Bar",
    art: "sunset",
    area: "Kralendijk",
    mapsQuery: "Karel's Beach Bar Bonaire",
    coordinates: { lat: 12.1519, lng: -68.2787, approximate: true },
    favorite: true,
    tags: ["favorite", "sunset", "drinks", "waterfront"],
    summary: l("Een drankje op een pier boven het water, precies op tijd voor de zonsondergang.", "A drink on a pier over the water, just in time for sunset."),
    whyWeRecommend: l(
      "Hier kijk je de zon letterlijk de zee in. Ideaal om de dag af te sluiten voor het diner.",
      "Watch the sun sink right into the sea. The perfect way to end the day before dinner.",
    ),
    tip: l("Kom een half uur voor zonsondergang voor de mooiste plekjes.", "Arrive half an hour before sunset for the best seats."),
    restaurant: { cuisine: l("Bar & snacks", "Bar & bites"), styles: ["waterfront", "sunset", "casual"], reservationRecommended: null },
    keywords: ["bar", "drinks", "borrel", "cocktail", "sunset", "zonsondergang", "bier", "beer"],
  },
  {
    id: "bobbejans",
    demo: true,
    category: "food",
    name: "Bobbejan's",
    art: "food",
    area: "Kralendijk",
    mapsQuery: "Bobbejan's Take Away Bonaire",
    coordinates: { lat: 12.1455, lng: -68.2718, approximate: true },
    tags: ["local", "dinner", "quick-bite"],
    summary: l("Een lokale favoriet voor ribs en saté, ongedwongen en gezellig.", "A local favourite for ribs and satay, casual and friendly."),
    whyWeRecommend: l("Geen poespas, wel heel veel smaak. Echt eilandgevoel.", "No frills, lots of flavour. Real island feel."),
    tip: l("Openingsdagen zijn beperkt — controleer ze vooraf.", "Opening days are limited — check before you go."),
    restaurant: { cuisine: l("BBQ & lokaal", "BBQ & local"), styles: ["meat", "local", "casual", "takeaway"], reservationRecommended: false },
    keywords: ["ribs", "bbq", "saté", "satay", "vlees", "meat", "lokaal", "local", "afhalen", "takeaway"],
  },
  {
    id: "capriccio",
    demo: true,
    category: "food",
    name: "Capriccio",
    art: "food",
    area: "Kralendijk",
    mapsQuery: "Capriccio Bonaire",
    coordinates: { lat: 12.1532, lng: -68.2780, approximate: true },
    tags: ["dinner", "romantic"],
    summary: l("Italiaans restaurant met huisgemaakte pasta en pizza.", "Italian restaurant with homemade pasta and pizza."),
    whyWeRecommend: l("Voor de avond dat je zin hebt in een goede pizza of pasta en een fijn glas wijn.", "For the evening you're craving a proper pizza or pasta and a good glass of wine."),
    restaurant: { cuisine: l("Italiaans", "Italian"), styles: ["international", "fine-dining"], reservationRecommended: true },
    keywords: ["italiaans", "italian", "pizza", "pasta", "wijn", "wine", "diner"],
  },
  {
    id: "between-2-buns",
    demo: true,
    category: "food",
    name: "Between 2 Buns",
    art: "coffee",
    area: "Kralendijk",
    mapsQuery: "Between 2 Buns Bonaire",
    coordinates: { lat: 12.1487, lng: -68.2757, approximate: true },
    tags: ["lunch", "quick-bite"],
    summary: l("Broodjes en lunch in het centrum — snel, vers en lekker.", "Sandwiches and lunch in town — quick, fresh and tasty."),
    whyWeRecommend: l("Handig tussen twee duiken of een ochtend in Kralendijk door.", "Perfect between two dives or during a morning in Kralendijk."),
    restaurant: { cuisine: l("Broodjes & lunch", "Sandwiches & lunch"), styles: ["lunch", "casual", "takeaway"], reservationRecommended: false },
    keywords: ["lunch", "broodje", "sandwich", "snel", "quick", "afhalen"],
  },
  {
    id: "cuba-compagnie",
    demo: true,
    category: "food",
    alsoIn: ["drinks"],
    name: "Cuba Compagnie",
    art: "night",
    area: "Kralendijk",
    mapsQuery: "Cuba Compagnie Bonaire",
    coordinates: { lat: 12.1505, lng: -68.2770, approximate: true },
    tags: ["dinner", "drinks"],
    summary: l("Levendige plek in het centrum voor diner en cocktails.", "Lively spot in town for dinner and cocktails."),
    whyWeRecommend: l("Leuk als je na het eten nog even wilt blijven hangen met een cocktail.", "Great if you feel like lingering over a cocktail after dinner."),
    restaurant: { cuisine: l("Latijns-Amerikaans geïnspireerd", "Latin-inspired"), styles: ["international", "casual"], reservationRecommended: null },
    keywords: ["cocktail", "diner", "dinner", "cuba", "muziek", "music", "uitgaan", "nightlife"],
  },
  {
    id: "la-cantina",
    demo: true,
    category: "drinks",
    alsoIn: ["food"],
    name: "La Cantina Cerveceria",
    art: "night",
    area: "Kralendijk",
    mapsQuery: "La Cantina Cerveceria Bonaire",
    coordinates: { lat: 12.1480, lng: -68.2745, approximate: true },
    tags: ["drinks", "dinner", "local"],
    summary: l("Brouwerij met eigen bieren en ongedwongen eten.", "Brewery with its own beers and casual food."),
    whyWeRecommend: l("Een lokaal gebrouwen biertje na een dag in de zon — wat wil je nog meer?", "A locally brewed beer after a day in the sun — what more do you need?"),
    restaurant: { cuisine: l("Brouwerij & grill", "Brewery & grill"), styles: ["casual", "meat"], reservationRecommended: null },
    keywords: ["bier", "beer", "brouwerij", "brewery", "borrel", "burger"],
  },
  {
    id: "jibe-city",
    demo: true,
    category: "food",
    alsoIn: ["drinks", "beaches"],
    name: "Jibe City",
    art: "wind",
    area: "Lac Bay / Sorobon",
    mapsQuery: "Jibe City Bonaire",
    coordinates: { lat: 12.1073, lng: -68.2276, approximate: true },
    tags: ["lunch", "waterfront", "after-the-beach"],
    summary: l("Strandbar aan Lac Bay, midden tussen de windsurfers.", "Beach bar on Lac Bay, right among the windsurfers."),
    whyWeRecommend: l("Lunch met je voeten in het zand en uitzicht op het ondiepe, turquoise water.", "Lunch with your toes in the sand and a view of the shallow turquoise bay."),
    restaurant: { cuisine: l("Strandlunch", "Beach lunch"), styles: ["lunch", "waterfront", "casual"], reservationRecommended: false },
    keywords: ["lac bay", "sorobon", "windsurf", "strand", "beach", "lunch", "bar"],
  },
  {
    id: "gelato",
    demo: true,
    category: "snacks",
    alsoIn: ["kids"],
    name: "Gio's Gelateria",
    art: "town",
    area: "Kralendijk",
    mapsQuery: "Gio's Gelateria Bonaire",
    coordinates: { lat: 12.1510, lng: -68.2775, approximate: true },
    tags: ["family", "quick-bite"],
    summary: l("Italiaans schepijs in het centrum van Kralendijk.", "Italian gelato in the centre of Kralendijk."),
    whyWeRecommend: l("De perfecte afsluiter van een wandeling over de boulevard.", "The perfect end to a stroll along the waterfront."),
    keywords: ["ijs", "ice cream", "gelato", "dessert", "kinderen", "kids"],
  },
  {
    id: "rum-runners",
    demo: true,
    category: "food",
    alsoIn: ["sunset"],
    name: "Rum Runners",
    art: "sunset",
    area: "Kralendijk (Captain Don's Habitat)",
    mapsQuery: "Rum Runners Captain Don's Habitat Bonaire",
    coordinates: { lat: 12.1690, lng: -68.2860, approximate: true },
    tags: ["dinner", "sunset", "waterfront"],
    summary: l("Restaurant aan het water bij een bekend duikresort, ideaal bij zonsondergang.", "Waterfront restaurant at a well-known dive resort, lovely at sunset."),
    whyWeRecommend: l("Ontspannen diner met de zee als decor.", "A relaxed dinner with the sea as your backdrop."),
    restaurant: { cuisine: l("Internationaal", "International"), styles: ["waterfront", "sunset", "international"], reservationRecommended: true },
    keywords: ["diner", "dinner", "sunset", "zee", "sea", "waterfront"],
  },
  {
    id: "coffee-placeholder",
    demo: true,
    category: "breakfast",
    name: l("[ONTBIJTZAAK INVULLEN]", "[TO FILL IN: BREAKFAST SPOT]"),
    art: "coffee",
    tags: ["breakfast"],
    summary: l("Plek voor jullie favoriete ontbijtadres en de beste koffie van het eiland.", "Space for your favourite breakfast spot and the best coffee on the island."),
    restaurant: { cuisine: l("Ontbijt & koffie", "Breakfast & coffee"), styles: ["breakfast"], reservationRecommended: null },
    keywords: ["ontbijt", "breakfast", "koffie", "coffee", "cappuccino", "brunch"],
  },
  {
    id: "foodtruck-placeholder",
    demo: true,
    category: "food",
    name: l("[FOODTRUCK INVULLEN]", "[TO FILL IN: FOOD TRUCK]"),
    art: "food",
    tags: ["local", "quick-bite"],
    summary: l("Plek voor een lokale foodtruck die jullie aanraden.", "Space for a local food truck you recommend."),
    restaurant: { cuisine: l("Lokaal", "Local"), styles: ["foodtruck", "local", "takeaway"], reservationRecommended: false },
    keywords: ["foodtruck", "food truck", "lokaal", "local", "snack", "pizza"],
  },
];
