/**
 * Interface texts. `en`, `es` and `de` are typed against `nl`, so a missing translation is a
 * TypeScript error — the app can never show a half-translated screen.
 */
const nl = {
  brand: {
    recommends: "Kas Daas raadt aan",
    ourBonaire: "Ons Bonaire",
    handpicked: "Met zorg gekozen",
    roadTrip: "Roadtrip",
    hiddenGems: "Verborgen parels",
    perfectDay: "De perfecte dag op Bonaire",
    private: "Privé",
  },
  welcome: {
    title: "Bon bini bij Kas Daas",
    text: "Deze gids is er speciaal voor onze gasten. Vul het wachtwoord in dat je van ons hebt gekregen.",
    password: "Wachtwoord",
    show: "Toon wachtwoord",
    submit: "Open de gids",
    wrong: "Dat wachtwoord klopt niet. Probeer het nog eens.",
    tooMany: "Te veel pogingen. Probeer het over een minuut opnieuw.",
    forgot: "Wachtwoord kwijt? Stuur Dennis een WhatsApp.",
    remember: "Je hoeft dit maar één keer te doen op dit apparaat.",
  },
  nav: { home: "Home", villa: "Villa", discover: "Ontdek", boat: "Boot", more: "Meer" },
  common: {
    search: "Zoeken",
    searchPlaceholder: "Zoek wifi, airco, pizza, snorkelen…",
    back: "Terug",
    home: "Home",
    route: "Route",
    call: "Bellen",
    whatsapp: "WhatsApp",
    website: "Website",
    reserve: "Reserveren",
    share: "Delen",
    copy: "Kopieer",
    copied: "Gekopieerd",
    viewAll: "Bekijk alles",
    more: "Meer",
    close: "Sluiten",
    open: "Openen",
    save: "Bewaar",
    saved: "Bewaard",
    remove: "Verwijder",
    demo: "Voorbeeld — nog te controleren",
    photoSoon: "Foto volgt",
    needsInternet: "Internet nodig",
    offline: "Offline — je bekijkt opgeslagen info",
    backOnline: "Weer online",
    language: "Taal",
    toTop: "Naar boven",
    minutes: "min",
    step: "Stap",
    tip: "Tip",
    reset: "Opnieuw",
    done: "Klaar",
    of: "van",
    notFoundTitle: "Deze pagina bestaat niet",
    notFoundText: "Misschien is hij verplaatst. Ga terug naar de start.",
    backHome: "Terug naar home",
    toFill: "Nog in te vullen",
    results: "resultaten",
    result: "resultaat",
    all: "Alles",
  },
  home: {
    greeting: "Bon bini bij Kas Daas",
    welcomeGuest: "Welkom in Kas Daas, {name}",
    tagline: "Jouw plek op Bonaire.",
    intro: "Alles voor een heerlijk verblijf — de villa, onze favoriete plekken en de boot. Altijd bij de hand, ook offline.",
    quick: "Snel naar",
    yourStay: "Jouw verblijf",
    arrival: "Aankomst",
    departure: "Vertrek",
    checkout: "Check-out",
    contactHost: "Contact host",
    discover: "Ontdek Bonaire",
    discoverText: "Onze persoonlijke tips, van rif tot restaurant.",
    villaGuide: "Villa-gids",
    villaGuideText: "Hoe alles werkt in Kas Daas.",
    ourBoat: "Onze boot",
    ourBoatText: "Bonaire vanaf het water.",
    favourites: "Kas Daas favorieten",
    favouritesText: "Plekken waar we zelf steeds weer naartoe gaan.",
    today: "Vandaag op Bonaire",
    todayMorning: "Goedemorgen. Snorkelen is ’s ochtends op z’n mooist.",
    todayAfternoon: "Middagzon? Tijd voor schaduw, lunch of Lac Bay.",
    todayEvening: "De zon gaat bijna onder. Waar kijk jij?",
    todayNight: "Tijd voor diner — of een rustige avond op het terras.",
    tonight: "Vanavond",
    tonightText: "Diner- en sunsetplekken die we aanraden.",
    dontMiss: "Niet missen",
    goodToKnow: "Handig om te weten",
    fromTheVilla: "Vanuit de villa",
    plans: "De perfecte dag op Bonaire",
    plansText: "Kant-en-klare dagplannen voor elk humeur.",
    install: "Kas Daas altijd bij de hand?",
    tipSun: "Zon",
    tipSunText: "Sterker dan je denkt",
    tipNature: "Natuur beschermen",
    tipNatureText: "Het rif is beschermd",
    tipMoney: "Geld & pinnen",
    tipMoneyText: "Amerikaanse dollar",
    tipTime: "Tijdzone",
    tipTimeText: "UTC−4, geen zomertijd",
  },
  quick: {
    about: "Over Kas Daas",
    wifi: "WiFi",
    route: "Route",
    food: "Eten & drinken",
    discover: "Ontdek Bonaire",
    boat: "Huur onze boot",
    help: "Hulp & contact",
    checkout: "Check-out",
  },
  villa: {
    title: "Villa-gids",
    subtitle: "Alles over Kas Daas, mooi op een rij.",
    duringStay: "Tijdens je verblijf",
    departureTitle: "Vertrek",
    departureSub: "Check-out checklist",
    helpTitle: "Hulp & problemen",
    helpSub: "Wat te doen als…",
    wifiTitle: "WiFi",
    wifiSub: "Netwerk & wachtwoord",
    confirmPresence: "Aanwezigheid nog te bevestigen",
    topics: "onderwerpen",
    steps: "Zo werkt het",
  },
  wifi: {
    network: "Netwerk",
    password: "Wachtwoord",
    copyPassword: "Kopieer wachtwoord",
    scan: "Scan om direct te verbinden",
    scanHint: "Open de camera op je telefoon en richt op de code.",
    coverage: "Bereik",
    router: "Router & storing",
    notSet: "Het wifi-wachtwoord wordt nog ingevuld door de beheerder.",
    connect: "Verbind met wifi",
    connectAndroid: "Kopieer wachtwoord & verbind",
    iosTitle: "Zo verbind je je iPhone",
    iosSteps: "Tik op ‘Verbind met wifi’ en kies ‘Sta toe’.|Open Instellingen en tik bovenaan op ‘Profiel gedownload’.|Tik op ‘Installeer’. Je iPhone verbindt daarna vanzelf met {ssid}.",
    iosNote: "Je iPhone meldt ‘Niet geverifieerd’: dat is normaal. Het profiel bevat alleen de wifi-gegevens van Kas Daas. Verwijderen kan later via Instellingen › Algemeen › VPN en apparaatbeheer.",
    androidTitle: "Zo verbind je je Android",
    androidSteps: "Tik op ‘Kopieer wachtwoord & verbind’.|Open Instellingen › Wifi (of veeg omlaag en houd het wifi-icoon ingedrukt).|Kies {ssid} en plak het wachtwoord.",
    otherTitle: "Verbinden",
    otherSteps: "Kies {ssid} in de wifi-lijst van je apparaat.|Vul het wachtwoord in, of kopieer het met de knop.",
    otherPhone: "Andere telefoon?",
    scanTitle: "Scan & verbind",
    scanText: "Richt de camera van een ander toestel op deze code en tik op de melding — je bent direct verbonden.",
  },
  departure: {
    title: "Vertrek",
    subtitle: "Check-out zonder zorgen",
    checkoutTime: "Check-outtijd",
    progress: "{done} van {total} gedaan",
    allDone: "Alles gedaan — goede reis!",
    resetList: "Lijst wissen",
  },
  help: {
    title: "Hulp & contact",
    subtitle: "We zijn er als je ons nodig hebt.",
    host: "Jouw house manager",
    availability: "Bereikbaarheid",
    emergency: "Noodnummers",
    emergencyText: "Bij direct gevaar: bel het alarmnummer.",
    problems: "Wat te doen als…",
    tryFirst: "Probeer eerst",
    stillStuck: "Lukt het niet?",
    messageHost: "Stuur de host een bericht",
    email: "E-mail",
    needHelp: "Hulp nodig?",
    yourLocation: "Jouw locatie (voor hulpdiensten)",
  },
  discover: {
    title: "Ontdek Bonaire",
    subtitle: "Ons Bonaire — plekken die we zelf graag bezoeken.",
    categories: "Categorieën",
    favourites: "Kas Daas favorieten",
    placesWeLove: "Plekken waar we van houden",
    filterTags: "Filter",
    empty: "Geen plekken gevonden. Probeer een ander filter.",
    map: "Kaart",
    plans: "Dagplannen",
    restaurants: "Restaurantgids",
    restaurantsText: "Handpicked restaurants — van strandlunch tot sunset-diner.",
    ourFavourites: "Onze favorieten",
    worthTheDrive: "Het ritje waard",
    perfectSunset: "Perfect voor sunset",
    searchIn: "Zoek in deze categorie",
  },
  place: {
    why: "Waarom wij dit aanraden",
    whyGo: "Waarom gaan?",
    oneOfOurFavourites: "Een van onze favorieten",
    kasDaasRecommends: "Kas Daas raadt aan",
    cuisine: "Keuken",
    price: "Prijsklasse",
    reservation: "Reserveren aanbevolen",
    yes: "Ja",
    no: "Nee",
    unknown: "Onbekend",
    location: "Locatie",
    travelTime: "Reistijd vanaf Kas Daas",
    hours: "Openingstijden",
    practicalTip: "Praktische tip",
    goodToKnow: "Goed om te weten",
    activity: "Zo haal je er het meeste uit",
    whyFun: "Waarom is dit leuk?",
    forWho: "Voor wie?",
    duration: "Hoeveel tijd?",
    bring: "Wat neem je mee?",
    bestTime: "Beste moment",
    diyOrBook: "Zelf doen of boeken?",
    keepInMind: "Waar let je op?",
    approximate: "Locatie bij benadering",
    related: "Ook de moeite waard",
    shareText: "Tip van Kas Daas:",
  },
  plans: {
    title: "Dagplannen",
    subtitle: "Inspiratie voor een perfecte dag — neem wat je leuk vindt.",
    day: "Dag",
    open: "Bekijk plan",
    suggestion: "Tijden zijn suggesties — op Bonaire heb je geen haast.",
  },
  map: {
    title: "Kaart",
    subtitle: "Onze tips op de kaart, met Kas Daas als thuisbasis.",
    home: "Kas Daas — thuisbasis",
    homePlaceholder: "Locatie van Kas Daas volgt",
    offline: "De kaartachtergrond heeft internet nodig. De lijst hieronder werkt altijd.",
    list: "Lijst",
    details: "Details",
    locate: "Mijn locatie",
  },
  favorites: {
    title: "Mijn Bonaire",
    subtitle: "Jouw bewaarde plekken, op dit apparaat.",
    empty: "Nog niets bewaard. Tik op het hartje bij een plek om hem hier te bewaren.",
    recent: "Recent bekeken",
    explore: "Ontdek plekken",
    add: "Bewaar in Mijn Bonaire",
    removeFav: "Verwijder uit Mijn Bonaire",
  },
  search: {
    title: "Zoeken",
    hint: "Probeer: wifi, airco, check-out, pizza, snorkelen, boot, supermarkt",
    none: "Niets gevonden voor “{q}”.",
    noneHint: "Probeer een ander woord, of vraag het de host.",
    types: { villa: "Villa", place: "Plek", plan: "Dagplan", practical: "Goed om te weten", help: "Hulp", boat: "Boot", page: "Pagina" },
  },
  more: {
    title: "Meer",
    subtitle: "Alles wat je verder nodig hebt.",
    guide: "Gids",
    app: "App",
    install: "Zet op beginscherm",
    installed: "Geïnstalleerd",
    about: "Over deze gids",
    aboutText: "Deze gids is gemaakt door de eigenaren van Kas Daas. Tips zijn persoonlijk — geen advertenties, geen ratings.",
    clearData: "Wis mijn gegevens op dit apparaat",
    clearDataText: "Favorieten, checklists en naam worden verwijderd.",
    cleared: "Gewist",
    offlineReady: "Klaar voor offline gebruik",
    offlineNotReady: "Offline opslag wordt voorbereid…",
  },
  practical: {
    title: "Goed om te weten op Bonaire",
    subtitle: "Praktische info voor een zorgeloze vakantie.",
    places: "Adressen",
  },
  install: {
    title: "Kas Daas altijd bij de hand?",
    text: "Zet de gids op je beginscherm. Hij opent dan als app — ook zonder internet.",
    button: "Zet op beginscherm",
    later: "Later",
    iosStep1: "Tik op Deel",
    iosStep2: "Kies ‘Zet op beginscherm’",
    iosHint: "In Safari, onderin je scherm",
  },
  boat: {
    rent: "Huur onze boot",
    facts: "Goed om te weten",
    included: "Inbegrepen",
    conditions: "Voorwaarden",
    ideas: "Ideeën voor een dag op het water",
    contact: "Stel je vraag via WhatsApp",
    call: "Bel ons",
    linkInvalid: "Deze bootlink is niet (meer) geldig. Neem contact op met de bootbeheerder voor een nieuwe link.",
  },
  boatGuide: {
    sos: "SOS / Hulp nodig",
    sosTitle: "Hulp nodig op het water?",
    sosText: "Blijf rustig. Zorg dat iedereen een reddingsvest draagt. Bel bij direct gevaar het alarmnummer.",
    sections: "Inhoud",
    location: "Waar ligt de boot",
    before: "Voor vertrek",
    start: "Boot starten",
    controls: "Bediening",
    safety: "Veiligheid",
    area: "Vaargebied",
    mooring: "Ankeren & aanleggen",
    anchoring: "Ankeren",
    docking: "Aanleggen",
    return: "Terugkomst",
    problems: "Problemen",
    contacts: "Contact",
    mediaSoon: "Foto/video volgt",
    areaSoon: "De kaart met het vaargebied wordt door de beheerder ingevuld.",
    solved: "Opgelost — goede vaart!",
    contactOwner: "Neem contact op met de beheerder",
    startOver: "Opnieuw",
    validUntil: "Toegang geldig tot",
    privateNote: "Deze pagina is privé en alleen voor huurders van de boot. Deel de link niet.",
    offlineSaved: "Deze handleiding is ook offline beschikbaar op dit apparaat tot je toegang verloopt.",
    forget: "Verwijder boot-info van dit apparaat",
    forgotten: "Verwijderd",
    zones: { allowed: "Toegestaan", forbidden: "Niet toegestaan", shallow: "Ondiep", danger: "Gevaarlijk", mooring: "Aanleggen / ankeren", poi: "Handige plek" },
    rules: "Aanleg- en ankerregels",
  },
};

type Dict = typeof nl;
type DeepString<T> = { [K in keyof T]: T[K] extends string ? string : DeepString<T[K]> };

const en: DeepString<Dict> = {
  brand: {
    recommends: "Kas Daas recommends",
    ourBonaire: "Our Bonaire",
    handpicked: "Handpicked",
    roadTrip: "Road trip",
    hiddenGems: "Hidden gems",
    perfectDay: "Perfect day on Bonaire",
    private: "Private",
  },
  welcome: {
    title: "Bon bini to Kas Daas",
    text: "This guide is made especially for our guests. Enter the password we sent you.",
    password: "Password",
    show: "Show password",
    submit: "Open the guide",
    wrong: "That password isn't right. Please try again.",
    tooMany: "Too many attempts. Please try again in a minute.",
    forgot: "Lost the password? Send Dennis a WhatsApp.",
    remember: "You only need to do this once on this device.",
  },
  nav: { home: "Home", villa: "Villa", discover: "Discover", boat: "Boat", more: "More" },
  common: {
    search: "Search",
    searchPlaceholder: "Search wifi, air con, pizza, snorkeling…",
    back: "Back",
    home: "Home",
    route: "Directions",
    call: "Call",
    whatsapp: "WhatsApp",
    website: "Website",
    reserve: "Reserve",
    share: "Share",
    copy: "Copy",
    copied: "Copied",
    viewAll: "View all",
    more: "More",
    close: "Close",
    open: "Open",
    save: "Save",
    saved: "Saved",
    remove: "Remove",
    demo: "Sample — to be verified",
    photoSoon: "Photo coming soon",
    needsInternet: "Needs internet",
    offline: "Offline — you're viewing saved info",
    backOnline: "Back online",
    language: "Language",
    toTop: "Back to top",
    minutes: "min",
    step: "Step",
    tip: "Tip",
    reset: "Reset",
    done: "Done",
    of: "of",
    notFoundTitle: "This page doesn't exist",
    notFoundText: "It may have moved. Head back to the start.",
    backHome: "Back to home",
    toFill: "To be filled in",
    results: "results",
    result: "result",
    all: "All",
  },
  home: {
    greeting: "Bon bini to Kas Daas",
    welcomeGuest: "Welcome to Kas Daas, {name}",
    tagline: "Your private place on Bonaire.",
    intro: "Everything for a wonderful stay — the villa, our favourite places and the boat. Always at hand, even offline.",
    quick: "Quick access",
    yourStay: "Your stay",
    arrival: "Arrival",
    departure: "Departure",
    checkout: "Check-out",
    contactHost: "Contact host",
    discover: "Discover Bonaire",
    discoverText: "Our personal picks, from reef to restaurant.",
    villaGuide: "Villa guide",
    villaGuideText: "How everything works at Kas Daas.",
    ourBoat: "Our boat",
    ourBoatText: "Bonaire from the water.",
    favourites: "Kas Daas favourites",
    favouritesText: "Places we keep going back to ourselves.",
    today: "Today on Bonaire",
    todayMorning: "Good morning. Snorkeling is at its best in the morning.",
    todayAfternoon: "Afternoon sun? Time for shade, lunch or Lac Bay.",
    todayEvening: "The sun is about to set. Where will you watch it?",
    todayNight: "Time for dinner — or a quiet evening on the terrace.",
    tonight: "Tonight",
    tonightText: "Dinner and sunset spots we recommend.",
    dontMiss: "Don't miss",
    goodToKnow: "Good to know",
    fromTheVilla: "From the villa",
    plans: "Perfect day on Bonaire",
    plansText: "Ready-made day plans for every mood.",
    install: "Keep Kas Daas at hand?",
    tipSun: "Sun",
    tipSunText: "Stronger than you think",
    tipNature: "Protect nature",
    tipNatureText: "The reef is protected",
    tipMoney: "Money & cards",
    tipMoneyText: "US dollar",
    tipTime: "Time zone",
    tipTimeText: "UTC−4, no daylight saving",
  },
  quick: {
    about: "About Kas Daas",
    wifi: "WiFi",
    route: "Directions",
    food: "Eat & drink",
    discover: "Discover Bonaire",
    boat: "Rent our boat",
    help: "Help & contact",
    checkout: "Check-out",
  },
  villa: {
    title: "Villa guide",
    subtitle: "Everything about Kas Daas, beautifully in one place.",
    duringStay: "During your stay",
    departureTitle: "Departure",
    departureSub: "Check-out checklist",
    helpTitle: "Help & issues",
    helpSub: "What to do if…",
    wifiTitle: "WiFi",
    wifiSub: "Network & password",
    confirmPresence: "Availability to be confirmed",
    topics: "topics",
    steps: "How it works",
  },
  wifi: {
    network: "Network",
    password: "Password",
    copyPassword: "Copy password",
    scan: "Scan to connect instantly",
    scanHint: "Open your phone's camera and point it at the code.",
    coverage: "Coverage",
    router: "Router & outages",
    notSet: "The WiFi password will be added by the host.",
    connect: "Connect to WiFi",
    connectAndroid: "Copy password & connect",
    iosTitle: "How to connect your iPhone",
    iosSteps: "Tap ‘Connect to WiFi’ and choose ‘Allow’.|Open Settings and tap ‘Profile Downloaded’ at the top.|Tap ‘Install’. Your iPhone then joins {ssid} automatically.",
    iosNote: "Your iPhone will say ‘Not Verified’: that's normal. The profile only contains the Kas Daas WiFi details. You can remove it later under Settings › General › VPN & Device Management.",
    androidTitle: "How to connect your Android",
    androidSteps: "Tap ‘Copy password & connect’.|Open Settings › Wi-Fi (or swipe down and long-press the Wi-Fi icon).|Choose {ssid} and paste the password.",
    otherTitle: "Connecting",
    otherSteps: "Choose {ssid} in your device's Wi-Fi list.|Enter the password, or copy it with the button.",
    otherPhone: "Different phone?",
    scanTitle: "Scan & connect",
    scanText: "Point another device's camera at this code and tap the notification — you're connected instantly.",
  },
  departure: {
    title: "Departure",
    subtitle: "A worry-free check-out",
    checkoutTime: "Check-out time",
    progress: "{done} of {total} done",
    allDone: "All done — safe travels!",
    resetList: "Clear list",
  },
  help: {
    title: "Help & contact",
    subtitle: "We're here when you need us.",
    host: "Your house manager",
    availability: "Availability",
    emergency: "Emergency numbers",
    emergencyText: "In immediate danger: call the emergency number.",
    problems: "What to do if…",
    tryFirst: "Try this first",
    stillStuck: "Still stuck?",
    messageHost: "Message the host",
    email: "Email",
    needHelp: "Need help?",
    yourLocation: "Your location (for emergency services)",
  },
  discover: {
    title: "Discover Bonaire",
    subtitle: "Our Bonaire — places we love to visit ourselves.",
    categories: "Categories",
    favourites: "Kas Daas favourites",
    placesWeLove: "Places we love",
    filterTags: "Filter",
    empty: "No places found. Try another filter.",
    map: "Map",
    plans: "Day plans",
    restaurants: "Restaurant guide",
    restaurantsText: "Handpicked restaurants — from beach lunch to sunset dinner.",
    ourFavourites: "Our favourites",
    worthTheDrive: "Worth the drive",
    perfectSunset: "Perfect for sunset",
    searchIn: "Search this category",
  },
  place: {
    why: "Why we recommend it",
    whyGo: "Why go?",
    oneOfOurFavourites: "One of our favourites",
    kasDaasRecommends: "Kas Daas recommends",
    cuisine: "Cuisine",
    price: "Price range",
    reservation: "Reservation recommended",
    yes: "Yes",
    no: "No",
    unknown: "Unknown",
    location: "Location",
    travelTime: "Travel time from Kas Daas",
    hours: "Opening hours",
    practicalTip: "Practical tip",
    goodToKnow: "Good to know",
    activity: "Making the most of it",
    whyFun: "Why it's great",
    forWho: "Who is it for?",
    duration: "How long?",
    bring: "What to bring",
    bestTime: "Best time",
    diyOrBook: "DIY or book?",
    keepInMind: "Keep in mind",
    approximate: "Approximate location",
    related: "Also worth it",
    shareText: "A tip from Kas Daas:",
  },
  plans: {
    title: "Day plans",
    subtitle: "Inspiration for a perfect day — take what you like.",
    day: "Day",
    open: "View plan",
    suggestion: "Times are suggestions — there's no rush on Bonaire.",
  },
  map: {
    title: "Map",
    subtitle: "Our tips on the map, with Kas Daas as your home base.",
    home: "Kas Daas — home base",
    homePlaceholder: "Kas Daas location coming soon",
    offline: "The map background needs internet. The list below always works.",
    list: "List",
    details: "Details",
    locate: "My location",
  },
  favorites: {
    title: "My Bonaire",
    subtitle: "Your saved places, on this device.",
    empty: "Nothing saved yet. Tap the heart on any place to keep it here.",
    recent: "Recently viewed",
    explore: "Explore places",
    add: "Save to My Bonaire",
    removeFav: "Remove from My Bonaire",
  },
  search: {
    title: "Search",
    hint: "Try: wifi, air con, check-out, pizza, snorkeling, boat, supermarket",
    none: "Nothing found for “{q}”.",
    noneHint: "Try another word, or ask the host.",
    types: { villa: "Villa", place: "Place", plan: "Day plan", practical: "Good to know", help: "Help", boat: "Boat", page: "Page" },
  },
  more: {
    title: "More",
    subtitle: "Everything else you might need.",
    guide: "Guide",
    app: "App",
    install: "Add to home screen",
    installed: "Installed",
    about: "About this guide",
    aboutText: "This guide was made by the owners of Kas Daas. Our tips are personal — no ads, no ratings.",
    clearData: "Clear my data on this device",
    clearDataText: "Favourites, checklists and your name will be removed.",
    cleared: "Cleared",
    offlineReady: "Ready for offline use",
    offlineNotReady: "Preparing offline storage…",
  },
  practical: {
    title: "Good to know on Bonaire",
    subtitle: "Practical info for a carefree holiday.",
    places: "Addresses",
  },
  install: {
    title: "Keep Kas Daas at hand?",
    text: "Add the guide to your home screen. It then opens like an app — even without internet.",
    button: "Add to home screen",
    later: "Later",
    iosStep1: "Tap Share",
    iosStep2: "Choose ‘Add to Home Screen’",
    iosHint: "In Safari, at the bottom of your screen",
  },
  boat: {
    rent: "Rent our boat",
    facts: "Good to know",
    included: "Included",
    conditions: "Conditions",
    ideas: "Ideas for a day on the water",
    contact: "Ask us on WhatsApp",
    call: "Call us",
    linkInvalid: "This boat link is no longer valid. Please contact the boat manager for a new link.",
  },
  boatGuide: {
    sos: "SOS / Need help",
    sosTitle: "Need help on the water?",
    sosText: "Stay calm. Make sure everyone wears a life jacket. In immediate danger, call the emergency number.",
    sections: "Contents",
    location: "Where the boat is",
    before: "Before you leave",
    start: "Starting the boat",
    controls: "Controls",
    safety: "Safety",
    area: "Boating area",
    mooring: "Anchoring & docking",
    anchoring: "Anchoring",
    docking: "Docking",
    return: "Coming back",
    problems: "Problems",
    contacts: "Contact",
    mediaSoon: "Photo/video coming soon",
    areaSoon: "The boating area map will be added by the owner.",
    solved: "Solved — enjoy the water!",
    contactOwner: "Contact the owner",
    startOver: "Start over",
    validUntil: "Access valid until",
    privateNote: "This page is private and only for boat renters. Please don't share the link.",
    offlineSaved: "This manual is also available offline on this device until your access expires.",
    forget: "Remove boat info from this device",
    forgotten: "Removed",
    zones: { allowed: "Permitted", forbidden: "Not permitted", shallow: "Shallow", danger: "Dangerous", mooring: "Mooring / anchoring", poi: "Useful spot" },
    rules: "Mooring and anchoring rules",
  },
};

const es: DeepString<Dict> = {
  brand: {
    recommends: "Kas Daas recomienda",
    ourBonaire: "Nuestro Bonaire",
    handpicked: "Escogido con cariño",
    roadTrip: "Ruta en coche",
    hiddenGems: "Joyas escondidas",
    perfectDay: "El día perfecto en Bonaire",
    private: "Privado",
  },
  welcome: {
    title: "Bon bini a Kas Daas",
    text: "Esta guía está hecha especialmente para nuestros huéspedes. Introduce la contraseña que te hemos enviado.",
    password: "Contraseña",
    show: "Mostrar contraseña",
    submit: "Abrir la guía",
    wrong: "La contraseña no es correcta. Inténtalo de nuevo.",
    tooMany: "Demasiados intentos. Vuelve a intentarlo dentro de un minuto.",
    forgot: "¿Has perdido la contraseña? Envía un WhatsApp a Dennis.",
    remember: "Solo tienes que hacerlo una vez en este dispositivo.",
  },
  nav: { home: "Inicio", villa: "Villa", discover: "Descubre", boat: "Barco", more: "Más" },
  common: {
    search: "Buscar",
    searchPlaceholder: "Busca wifi, aire, pizza, snorkel…",
    back: "Atrás",
    home: "Inicio",
    route: "Ruta",
    call: "Llamar",
    whatsapp: "WhatsApp",
    website: "Web",
    reserve: "Reservar",
    share: "Compartir",
    copy: "Copiar",
    copied: "Copiado",
    viewAll: "Ver todo",
    more: "Más",
    close: "Cerrar",
    open: "Abrir",
    save: "Guardar",
    saved: "Guardado",
    remove: "Quitar",
    demo: "Ejemplo — pendiente de verificar",
    photoSoon: "Foto próximamente",
    needsInternet: "Requiere internet",
    offline: "Sin conexión — estás viendo información guardada",
    backOnline: "De nuevo en línea",
    language: "Idioma",
    toTop: "Volver arriba",
    minutes: "min",
    step: "Paso",
    tip: "Consejo",
    reset: "Reiniciar",
    done: "Listo",
    of: "de",
    notFoundTitle: "Esta página no existe",
    notFoundText: "Puede que se haya movido. Vuelve al inicio.",
    backHome: "Volver al inicio",
    toFill: "Por completar",
    results: "resultados",
    result: "resultado",
    all: "Todo",
  },
  home: {
    greeting: "Bon bini a Kas Daas",
    welcomeGuest: "Bienvenido a Kas Daas, {name}",
    tagline: "Tu rincón privado en Bonaire.",
    intro: "Todo para una estancia maravillosa: la villa, nuestros lugares favoritos y el barco. Siempre a mano, incluso sin conexión.",
    quick: "Acceso rápido",
    yourStay: "Tu estancia",
    arrival: "Llegada",
    departure: "Salida",
    checkout: "Check-out",
    contactHost: "Contactar con el anfitrión",
    discover: "Descubre Bonaire",
    discoverText: "Nuestras recomendaciones personales, del arrecife al restaurante.",
    villaGuide: "Guía de la villa",
    villaGuideText: "Cómo funciona todo en Kas Daas.",
    ourBoat: "Nuestro barco",
    ourBoatText: "Bonaire desde el agua.",
    favourites: "Favoritos de Kas Daas",
    favouritesText: "Lugares a los que nosotros mismos siempre volvemos.",
    today: "Hoy en Bonaire",
    todayMorning: "Buenos días. Por la mañana es cuando mejor se hace snorkel.",
    todayAfternoon: "¿Sol de tarde? Hora de sombra, de almorzar o de ir a Lac Bay.",
    todayEvening: "El sol está a punto de ponerse. ¿Desde dónde lo verás?",
    todayNight: "Hora de cenar, o de una velada tranquila en la terraza.",
    tonight: "Esta noche",
    tonightText: "Sitios para cenar y ver el atardecer que te recomendamos.",
    dontMiss: "No te lo pierdas",
    goodToKnow: "Bueno saber",
    fromTheVilla: "Desde la villa",
    plans: "El día perfecto en Bonaire",
    plansText: "Planes de día listos para cada estado de ánimo.",
    install: "¿Quieres tener Kas Daas siempre a mano?",
    tipSun: "Sol",
    tipSunText: "Más fuerte de lo que crees",
    tipNature: "Protege la naturaleza",
    tipNatureText: "El arrecife está protegido",
    tipMoney: "Dinero y tarjetas",
    tipMoneyText: "Dólar estadounidense",
    tipTime: "Zona horaria",
    tipTimeText: "UTC−4, sin horario de verano",
  },
  quick: {
    about: "Sobre Kas Daas",
    wifi: "Wifi",
    route: "Ruta",
    food: "Comer y beber",
    discover: "Descubre Bonaire",
    boat: "Alquila nuestro barco",
    help: "Ayuda y contacto",
    checkout: "Check-out",
  },
  villa: {
    title: "Guía de la villa",
    subtitle: "Todo sobre Kas Daas, reunido en un solo lugar.",
    duringStay: "Durante tu estancia",
    departureTitle: "Salida",
    departureSub: "Lista para el check-out",
    helpTitle: "Ayuda e incidencias",
    helpSub: "Qué hacer si…",
    wifiTitle: "Wifi",
    wifiSub: "Red y contraseña",
    confirmPresence: "Disponibilidad por confirmar",
    topics: "temas",
    steps: "Cómo funciona",
  },
  wifi: {
    network: "Red",
    password: "Contraseña",
    copyPassword: "Copiar contraseña",
    scan: "Escanea para conectarte al instante",
    scanHint: "Abre la cámara de tu teléfono y apunta al código.",
    coverage: "Cobertura",
    router: "Router y cortes",
    notSet: "El anfitrión añadirá la contraseña del wifi.",
    connect: "Conectarse al wifi",
    connectAndroid: "Copiar contraseña y conectar",
    iosTitle: "Cómo conectar tu iPhone",
    iosSteps: "Toca ‘Conectarse al wifi’ y elige ‘Permitir’.|Abre Ajustes y toca ‘Perfil descargado’ arriba del todo.|Toca ‘Instalar’. Tu iPhone se conectará automáticamente a {ssid}.",
    iosNote: "Tu iPhone indicará ‘No verificado’: es normal. El perfil solo contiene los datos del wifi de Kas Daas. Puedes eliminarlo después en Ajustes › General › VPN y gestión de dispositivos.",
    androidTitle: "Cómo conectar tu Android",
    androidSteps: "Toca ‘Copiar contraseña y conectar’.|Abre Ajustes › Wi-Fi (o desliza hacia abajo y mantén pulsado el icono de Wi-Fi).|Elige {ssid} y pega la contraseña.",
    otherTitle: "Conectarse",
    otherSteps: "Elige {ssid} en la lista de redes Wi-Fi de tu dispositivo.|Introduce la contraseña o cópiala con el botón.",
    otherPhone: "¿Otro teléfono?",
    scanTitle: "Escanear y conectar",
    scanText: "Apunta la cámara de otro dispositivo a este código y toca la notificación: te conectarás al instante.",
  },
  departure: {
    title: "Salida",
    subtitle: "Un check-out sin preocupaciones",
    checkoutTime: "Hora del check-out",
    progress: "{done} de {total} hechos",
    allDone: "¡Todo listo! Buen viaje.",
    resetList: "Vaciar lista",
  },
  help: {
    title: "Ayuda y contacto",
    subtitle: "Estamos aquí cuando nos necesites.",
    host: "Tu encargado de la casa",
    availability: "Disponibilidad",
    emergency: "Números de emergencia",
    emergencyText: "Si hay peligro inmediato: llama al número de emergencia.",
    problems: "Qué hacer si…",
    tryFirst: "Prueba esto primero",
    stillStuck: "¿Sigues sin solución?",
    messageHost: "Escribe al anfitrión",
    email: "Correo electrónico",
    needHelp: "¿Necesitas ayuda?",
    yourLocation: "Tu ubicación (para los servicios de emergencia)",
  },
  discover: {
    title: "Descubre Bonaire",
    subtitle: "Nuestro Bonaire: lugares que nos encanta visitar.",
    categories: "Categorías",
    favourites: "Favoritos de Kas Daas",
    placesWeLove: "Lugares que nos encantan",
    filterTags: "Filtrar",
    empty: "No se han encontrado lugares. Prueba con otro filtro.",
    map: "Mapa",
    plans: "Planes de día",
    restaurants: "Guía de restaurantes",
    restaurantsText: "Restaurantes escogidos con cariño: del almuerzo en la playa a la cena al atardecer.",
    ourFavourites: "Nuestros favoritos",
    worthTheDrive: "Merece el viaje",
    perfectSunset: "Perfecto para el atardecer",
    searchIn: "Buscar en esta categoría",
  },
  place: {
    why: "Por qué lo recomendamos",
    whyGo: "¿Por qué ir?",
    oneOfOurFavourites: "Uno de nuestros favoritos",
    kasDaasRecommends: "Kas Daas recomienda",
    cuisine: "Cocina",
    price: "Rango de precios",
    reservation: "Se recomienda reservar",
    yes: "Sí",
    no: "No",
    unknown: "Desconocido",
    location: "Ubicación",
    travelTime: "Tiempo de viaje desde Kas Daas",
    hours: "Horario",
    practicalTip: "Consejo práctico",
    goodToKnow: "Bueno saber",
    activity: "Cómo sacarle el máximo partido",
    whyFun: "Por qué merece la pena",
    forWho: "¿Para quién es?",
    duration: "¿Cuánto tiempo?",
    bring: "Qué llevar",
    bestTime: "Mejor momento",
    diyOrBook: "¿Por tu cuenta o reservando?",
    keepInMind: "Ten en cuenta",
    approximate: "Ubicación aproximada",
    related: "También merece la pena",
    shareText: "Un consejo de Kas Daas:",
  },
  plans: {
    title: "Planes de día",
    subtitle: "Inspiración para un día perfecto: quédate con lo que te guste.",
    day: "Día",
    open: "Ver plan",
    suggestion: "Los horarios son sugerencias: en Bonaire no hay prisa.",
  },
  map: {
    title: "Mapa",
    subtitle: "Nuestros consejos en el mapa, con Kas Daas como base.",
    home: "Kas Daas — tu base",
    homePlaceholder: "Ubicación de Kas Daas próximamente",
    offline: "El fondo del mapa necesita internet. La lista de abajo siempre funciona.",
    list: "Lista",
    details: "Detalles",
    locate: "Mi ubicación",
  },
  favorites: {
    title: "Mi Bonaire",
    subtitle: "Tus lugares guardados, en este dispositivo.",
    empty: "Todavía no has guardado nada. Toca el corazón de cualquier lugar para guardarlo aquí.",
    recent: "Vistos recientemente",
    explore: "Explorar lugares",
    add: "Guardar en Mi Bonaire",
    removeFav: "Quitar de Mi Bonaire",
  },
  search: {
    title: "Buscar",
    hint: "Prueba: wifi, aire acondicionado, check-out, pizza, snorkel, barco, supermercado",
    none: "No se ha encontrado nada para “{q}”.",
    noneHint: "Prueba con otra palabra o pregunta al anfitrión.",
    types: { villa: "Villa", place: "Lugar", plan: "Plan de día", practical: "Bueno saber", help: "Ayuda", boat: "Barco", page: "Página" },
  },
  more: {
    title: "Más",
    subtitle: "Todo lo demás que puedas necesitar.",
    guide: "Guía",
    app: "App",
    install: "Añadir a la pantalla de inicio",
    installed: "Instalada",
    about: "Sobre esta guía",
    aboutText: "Esta guía la han hecho los propietarios de Kas Daas. Nuestros consejos son personales: sin anuncios ni valoraciones.",
    clearData: "Borrar mis datos de este dispositivo",
    clearDataText: "Se eliminarán tus favoritos, las listas y tu nombre.",
    cleared: "Borrado",
    offlineReady: "Lista para usar sin conexión",
    offlineNotReady: "Preparando el almacenamiento sin conexión…",
  },
  practical: {
    title: "Bueno saber en Bonaire",
    subtitle: "Información práctica para unas vacaciones sin preocupaciones.",
    places: "Direcciones",
  },
  install: {
    title: "¿Quieres tener Kas Daas siempre a mano?",
    text: "Añade la guía a tu pantalla de inicio. Se abrirá como una app, incluso sin internet.",
    button: "Añadir a la pantalla de inicio",
    later: "Más tarde",
    iosStep1: "Toca Compartir",
    iosStep2: "Elige ‘Añadir a pantalla de inicio’",
    iosHint: "En Safari, en la parte inferior de la pantalla",
  },
  boat: {
    rent: "Alquila nuestro barco",
    facts: "Bueno saber",
    included: "Incluido",
    conditions: "Condiciones",
    ideas: "Ideas para un día en el agua",
    contact: "Pregúntanos por WhatsApp",
    call: "Llámanos",
    linkInvalid: "Este enlace del barco ya no es válido. Contacta con el encargado del barco para obtener un enlace nuevo.",
  },
  boatGuide: {
    sos: "SOS / Necesito ayuda",
    sosTitle: "¿Necesitas ayuda en el agua?",
    sosText: "Mantén la calma. Asegúrate de que todos llevan chaleco salvavidas. Si hay peligro inmediato, llama al número de emergencia.",
    sections: "Contenido",
    location: "Dónde está el barco",
    before: "Antes de salir",
    start: "Arrancar el barco",
    controls: "Mandos",
    safety: "Seguridad",
    area: "Zona de navegación",
    mooring: "Fondear y atracar",
    anchoring: "Fondear",
    docking: "Atracar",
    return: "Al volver",
    problems: "Problemas",
    contacts: "Contacto",
    mediaSoon: "Foto/vídeo próximamente",
    areaSoon: "El propietario añadirá el mapa de la zona de navegación.",
    solved: "¡Resuelto! Disfruta del agua.",
    contactOwner: "Contacta con el propietario",
    startOver: "Empezar de nuevo",
    validUntil: "Acceso válido hasta",
    privateNote: "Esta página es privada y solo para quienes alquilan el barco. No compartas el enlace.",
    offlineSaved: "Este manual también está disponible sin conexión en este dispositivo hasta que caduque tu acceso.",
    forget: "Eliminar la información del barco de este dispositivo",
    forgotten: "Eliminado",
    zones: { allowed: "Permitido", forbidden: "No permitido", shallow: "Poco profundo", danger: "Peligroso", mooring: "Amarre / fondeo", poi: "Lugar útil" },
    rules: "Normas de amarre y fondeo",
  },
};

const de: DeepString<Dict> = {
  brand: {
    recommends: "Kas Daas empfiehlt",
    ourBonaire: "Unser Bonaire",
    handpicked: "Handverlesen",
    roadTrip: "Roadtrip",
    hiddenGems: "Geheimtipps",
    perfectDay: "Der perfekte Tag auf Bonaire",
    private: "Privat",
  },
  welcome: {
    title: "Bon bini im Kas Daas",
    text: "Dieser Guide ist speziell für unsere Gäste gemacht. Gib das Passwort ein, das du von uns bekommen hast.",
    password: "Passwort",
    show: "Passwort anzeigen",
    submit: "Guide öffnen",
    wrong: "Das Passwort stimmt nicht. Versuch es noch einmal.",
    tooMany: "Zu viele Versuche. Versuch es in einer Minute erneut.",
    forgot: "Passwort vergessen? Schick Dennis eine WhatsApp.",
    remember: "Das musst du auf diesem Gerät nur einmal machen.",
  },
  nav: { home: "Start", villa: "Villa", discover: "Entdecken", boat: "Boot", more: "Mehr" },
  common: {
    search: "Suchen",
    searchPlaceholder: "Suche WLAN, Klima, Pizza…",
    back: "Zurück",
    home: "Start",
    route: "Route",
    call: "Anrufen",
    whatsapp: "WhatsApp",
    website: "Website",
    reserve: "Reservieren",
    share: "Teilen",
    copy: "Kopieren",
    copied: "Kopiert",
    viewAll: "Alle ansehen",
    more: "Mehr",
    close: "Schließen",
    open: "Öffnen",
    save: "Merken",
    saved: "Gemerkt",
    remove: "Entfernen",
    demo: "Beispiel – noch zu prüfen",
    photoSoon: "Foto folgt",
    needsInternet: "Internet nötig",
    offline: "Offline – du siehst gespeicherte Infos",
    backOnline: "Wieder online",
    language: "Sprache",
    toTop: "Nach oben",
    minutes: "Min.",
    step: "Schritt",
    tip: "Tipp",
    reset: "Zurücksetzen",
    done: "Fertig",
    of: "von",
    notFoundTitle: "Diese Seite gibt es nicht",
    notFoundText: "Vielleicht wurde sie verschoben. Geh zurück zum Start.",
    backHome: "Zurück zum Start",
    toFill: "Noch zu ergänzen",
    results: "Ergebnisse",
    result: "Ergebnis",
    all: "Alle",
  },
  home: {
    greeting: "Bon bini im Kas Daas",
    welcomeGuest: "Willkommen im Kas Daas, {name}",
    tagline: "Dein privater Ort auf Bonaire.",
    intro: "Alles für einen wunderbaren Aufenthalt – die Villa, unsere Lieblingsorte und das Boot. Immer griffbereit, auch offline.",
    quick: "Schnellzugriff",
    yourStay: "Dein Aufenthalt",
    arrival: "Ankunft",
    departure: "Abreise",
    checkout: "Check-out",
    contactHost: "Gastgeber kontaktieren",
    discover: "Bonaire entdecken",
    discoverText: "Unsere persönlichen Tipps, vom Riff bis zum Restaurant.",
    villaGuide: "Villa-Guide",
    villaGuideText: "Wie im Kas Daas alles funktioniert.",
    ourBoat: "Unser Boot",
    ourBoatText: "Bonaire vom Wasser aus.",
    favourites: "Kas-Daas-Favoriten",
    favouritesText: "Orte, an die wir selbst immer wieder zurückkehren.",
    today: "Heute auf Bonaire",
    todayMorning: "Guten Morgen. Morgens ist das Schnorcheln am schönsten.",
    todayAfternoon: "Nachmittagssonne? Zeit für Schatten, Mittagessen oder die Lac Bay.",
    todayEvening: "Gleich geht die Sonne unter. Wo schaust du zu?",
    todayNight: "Zeit fürs Abendessen – oder einen ruhigen Abend auf der Terrasse.",
    tonight: "Heute Abend",
    tonightText: "Restaurants und Sonnenuntergangsplätze, die wir empfehlen.",
    dontMiss: "Nicht verpassen",
    goodToKnow: "Gut zu wissen",
    fromTheVilla: "Ab der Villa",
    plans: "Der perfekte Tag auf Bonaire",
    plansText: "Fertige Tagespläne für jede Stimmung.",
    install: "Kas Daas immer griffbereit?",
    tipSun: "Sonne",
    tipSunText: "Stärker, als du denkst",
    tipNature: "Natur schützen",
    tipNatureText: "Das Riff ist geschützt",
    tipMoney: "Geld & Karten",
    tipMoneyText: "US-Dollar",
    tipTime: "Zeitzone",
    tipTimeText: "UTC−4, keine Sommerzeit",
  },
  quick: {
    about: "Über Kas Daas",
    wifi: "WLAN",
    route: "Route",
    food: "Essen & Trinken",
    discover: "Bonaire entdecken",
    boat: "Unser Boot mieten",
    help: "Hilfe & Kontakt",
    checkout: "Check-out",
  },
  villa: {
    title: "Villa-Guide",
    subtitle: "Alles über Kas Daas, schön an einem Ort.",
    duringStay: "Während deines Aufenthalts",
    departureTitle: "Abreise",
    departureSub: "Check-out-Checkliste",
    helpTitle: "Hilfe & Probleme",
    helpSub: "Was tun, wenn…",
    wifiTitle: "WLAN",
    wifiSub: "Netzwerk & Passwort",
    confirmPresence: "Erreichbarkeit noch zu bestätigen",
    topics: "Themen",
    steps: "So funktioniert's",
  },
  wifi: {
    network: "Netzwerk",
    password: "Passwort",
    copyPassword: "Passwort kopieren",
    scan: "Scannen und sofort verbinden",
    scanHint: "Öffne die Kamera deines Handys und richte sie auf den Code.",
    coverage: "Abdeckung",
    router: "Router & Störungen",
    notSet: "Das WLAN-Passwort wird vom Gastgeber ergänzt.",
    connect: "Mit WLAN verbinden",
    connectAndroid: "Passwort kopieren & verbinden",
    iosTitle: "So verbindest du dein iPhone",
    iosSteps: "Tippe auf ‚Mit WLAN verbinden‘ und wähle ‚Zulassen‘.|Öffne die Einstellungen und tippe oben auf ‚Profil geladen‘.|Tippe auf ‚Installieren‘. Dein iPhone verbindet sich dann automatisch mit {ssid}.",
    iosNote: "Dein iPhone zeigt ‚Nicht überprüft‘ an: Das ist normal. Das Profil enthält nur die WLAN-Daten von Kas Daas. Du kannst es später unter Einstellungen › Allgemein › VPN und Geräteverwaltung entfernen.",
    androidTitle: "So verbindest du dein Android",
    androidSteps: "Tippe auf ‚Passwort kopieren & verbinden‘.|Öffne Einstellungen › WLAN (oder wische nach unten und halte das WLAN-Symbol gedrückt).|Wähle {ssid} und füge das Passwort ein.",
    otherTitle: "Verbinden",
    otherSteps: "Wähle {ssid} in der WLAN-Liste deines Geräts.|Gib das Passwort ein oder kopiere es mit der Taste.",
    otherPhone: "Anderes Handy?",
    scanTitle: "Scannen & verbinden",
    scanText: "Richte die Kamera eines anderen Geräts auf diesen Code und tippe auf die Meldung – schon bist du verbunden.",
  },
  departure: {
    title: "Abreise",
    subtitle: "Ein sorgenfreier Check-out",
    checkoutTime: "Check-out-Zeit",
    progress: "{done} von {total} erledigt",
    allDone: "Alles erledigt – gute Reise!",
    resetList: "Liste leeren",
  },
  help: {
    title: "Hilfe & Kontakt",
    subtitle: "Wir sind da, wenn du uns brauchst.",
    host: "Dein Hausverwalter",
    availability: "Erreichbarkeit",
    emergency: "Notrufnummern",
    emergencyText: "Bei akuter Gefahr: Ruf den Notruf an.",
    problems: "Was tun, wenn…",
    tryFirst: "Probier zuerst das",
    stillStuck: "Klappt es immer noch nicht?",
    messageHost: "Gastgeber anschreiben",
    email: "E-Mail",
    needHelp: "Brauchst du Hilfe?",
    yourLocation: "Dein Standort (für den Rettungsdienst)",
  },
  discover: {
    title: "Bonaire entdecken",
    subtitle: "Unser Bonaire – Orte, die wir selbst gern besuchen.",
    categories: "Kategorien",
    favourites: "Kas-Daas-Favoriten",
    placesWeLove: "Orte, die wir lieben",
    filterTags: "Filtern",
    empty: "Keine Orte gefunden. Probier einen anderen Filter.",
    map: "Karte",
    plans: "Tagespläne",
    restaurants: "Restaurantführer",
    restaurantsText: "Handverlesene Restaurants – vom Strand-Lunch bis zum Dinner bei Sonnenuntergang.",
    ourFavourites: "Unsere Favoriten",
    worthTheDrive: "Die Fahrt wert",
    perfectSunset: "Perfekt zum Sonnenuntergang",
    searchIn: "In dieser Kategorie suchen",
  },
  place: {
    why: "Warum wir es empfehlen",
    whyGo: "Warum hin?",
    oneOfOurFavourites: "Einer unserer Favoriten",
    kasDaasRecommends: "Kas Daas empfiehlt",
    cuisine: "Küche",
    price: "Preisklasse",
    reservation: "Reservierung empfohlen",
    yes: "Ja",
    no: "Nein",
    unknown: "Unbekannt",
    location: "Lage",
    travelTime: "Fahrzeit ab Kas Daas",
    hours: "Öffnungszeiten",
    practicalTip: "Praktischer Tipp",
    goodToKnow: "Gut zu wissen",
    activity: "Das Beste daraus machen",
    whyFun: "Warum es toll ist",
    forWho: "Für wen?",
    duration: "Wie lange?",
    bring: "Was mitnehmen",
    bestTime: "Beste Zeit",
    diyOrBook: "Selbst machen oder buchen?",
    keepInMind: "Beachte",
    approximate: "Ungefähre Lage",
    related: "Auch lohnenswert",
    shareText: "Ein Tipp von Kas Daas:",
  },
  plans: {
    title: "Tagespläne",
    subtitle: "Inspiration für einen perfekten Tag – nimm, was dir gefällt.",
    day: "Tag",
    open: "Plan ansehen",
    suggestion: "Die Zeiten sind Vorschläge – auf Bonaire hat niemand Eile.",
  },
  map: {
    title: "Karte",
    subtitle: "Unsere Tipps auf der Karte, mit Kas Daas als Ausgangspunkt.",
    home: "Kas Daas – Ausgangspunkt",
    homePlaceholder: "Lage von Kas Daas folgt",
    offline: "Der Kartenhintergrund braucht Internet. Die Liste unten funktioniert immer.",
    list: "Liste",
    details: "Details",
    locate: "Mein Standort",
  },
  favorites: {
    title: "Mein Bonaire",
    subtitle: "Deine gemerkten Orte, auf diesem Gerät.",
    empty: "Noch nichts gemerkt. Tippe bei einem Ort auf das Herz, um ihn hier zu speichern.",
    recent: "Zuletzt angesehen",
    explore: "Orte entdecken",
    add: "In Mein Bonaire merken",
    removeFav: "Aus Mein Bonaire entfernen",
  },
  search: {
    title: "Suchen",
    hint: "Probier: WLAN, Klimaanlage, Check-out, Pizza, Schnorcheln, Boot, Supermarkt",
    none: "Nichts gefunden für „{q}“.",
    noneHint: "Probier ein anderes Wort oder frag den Gastgeber.",
    types: { villa: "Villa", place: "Ort", plan: "Tagesplan", practical: "Gut zu wissen", help: "Hilfe", boat: "Boot", page: "Seite" },
  },
  more: {
    title: "Mehr",
    subtitle: "Alles andere, was du brauchen könntest.",
    guide: "Guide",
    app: "App",
    install: "Zum Home-Bildschirm",
    installed: "Installiert",
    about: "Über diesen Guide",
    aboutText: "Dieser Guide wurde von den Eigentümern von Kas Daas gemacht. Unsere Tipps sind persönlich – keine Werbung, keine Bewertungen.",
    clearData: "Meine Daten auf diesem Gerät löschen",
    clearDataText: "Favoriten, Checklisten und dein Name werden entfernt.",
    cleared: "Gelöscht",
    offlineReady: "Bereit für die Offline-Nutzung",
    offlineNotReady: "Offline-Speicher wird vorbereitet…",
  },
  practical: {
    title: "Gut zu wissen auf Bonaire",
    subtitle: "Praktische Infos für einen sorgenfreien Urlaub.",
    places: "Adressen",
  },
  install: {
    title: "Kas Daas immer griffbereit?",
    text: "Füge den Guide zu deinem Home-Bildschirm hinzu. Dann öffnet er sich wie eine App – auch ohne Internet.",
    button: "Zum Home-Bildschirm",
    later: "Später",
    iosStep1: "Tippe auf Teilen",
    iosStep2: "Wähle ‚Zum Home-Bildschirm‘",
    iosHint: "In Safari, unten auf deinem Bildschirm",
  },
  boat: {
    rent: "Unser Boot mieten",
    facts: "Gut zu wissen",
    included: "Inklusive",
    conditions: "Bedingungen",
    ideas: "Ideen für einen Tag auf dem Wasser",
    contact: "Frag uns per WhatsApp",
    call: "Ruf uns an",
    linkInvalid: "Dieser Bootslink ist nicht mehr gültig. Wende dich an den Bootsverwalter, um einen neuen Link zu bekommen.",
  },
  boatGuide: {
    sos: "SOS / Hilfe",
    sosTitle: "Brauchst du Hilfe auf dem Wasser?",
    sosText: "Bleib ruhig. Sorg dafür, dass alle eine Rettungsweste tragen. Bei akuter Gefahr ruf den Notruf an.",
    sections: "Inhalt",
    location: "Wo das Boot liegt",
    before: "Bevor du ablegst",
    start: "Das Boot starten",
    controls: "Bedienung",
    safety: "Sicherheit",
    area: "Fahrgebiet",
    mooring: "Ankern & Anlegen",
    anchoring: "Ankern",
    docking: "Anlegen",
    return: "Rückkehr",
    problems: "Probleme",
    contacts: "Kontakt",
    mediaSoon: "Foto/Video folgt",
    areaSoon: "Die Karte des Fahrgebiets wird vom Eigentümer ergänzt.",
    solved: "Gelöst – viel Spaß auf dem Wasser!",
    contactOwner: "Eigentümer kontaktieren",
    startOver: "Neu beginnen",
    validUntil: "Zugang gültig bis",
    privateNote: "Diese Seite ist privat und nur für Bootsmieter. Bitte teile den Link nicht.",
    offlineSaved: "Diese Anleitung ist auf diesem Gerät auch offline verfügbar, bis dein Zugang abläuft.",
    forget: "Bootsinfos von diesem Gerät entfernen",
    forgotten: "Entfernt",
    zones: { allowed: "Erlaubt", forbidden: "Nicht erlaubt", shallow: "Flach", danger: "Gefährlich", mooring: "Anlegen / Ankern", poi: "Nützlicher Ort" },
    rules: "Regeln zum Anlegen und Ankern",
  },
};

export const dictionaries = { nl, en, es, de };
export type Dictionary = DeepString<Dict>;

/** Replace {placeholders} in a string. */
export function fmt(template: string, vars: Record<string, string | number>): string {
  return template.replace(/\{(\w+)\}/g, (_, k) => String(vars[k] ?? ""));
}
