/**
 * Interface texts. `en` is typed against `nl`, so a missing translation is a
 * TypeScript error — the app can never show a half-translated screen.
 */
const nl = {
  brand: {
    recommends: "Kas Daas raadt aan",
    ourBonaire: "Ons Bonaire",
    handpicked: "Met zorg gekozen",
    roadTrip: "Roadtrip",
    hiddenGems: "Verborgen parels",
    perfectDay: "De perfecte dag op Bonaire",
    private: "Privé",
  },
  nav: { home: "Home", villa: "Villa", discover: "Ontdek", boat: "Boot", more: "Meer" },
  common: {
    search: "Zoeken",
    searchPlaceholder: "Zoek wifi, airco, pizza, snorkelen…",
    back: "Terug",
    home: "Home",
    route: "Route",
    call: "Bellen",
    whatsapp: "WhatsApp",
    website: "Website",
    reserve: "Reserveren",
    share: "Delen",
    copy: "Kopieer",
    copied: "Gekopieerd",
    viewAll: "Bekijk alles",
    more: "Meer",
    close: "Sluiten",
    open: "Openen",
    save: "Bewaar",
    saved: "Bewaard",
    remove: "Verwijder",
    demo: "Voorbeeld — nog te controleren",
    photoSoon: "Foto volgt",
    needsInternet: "Internet nodig",
    offline: "Offline — je bekijkt opgeslagen info",
    backOnline: "Weer online",
    language: "Taal",
    toTop: "Naar boven",
    minutes: "min",
    step: "Stap",
    tip: "Tip",
    reset: "Opnieuw",
    done: "Klaar",
    of: "van",
    notFoundTitle: "Deze pagina bestaat niet",
    notFoundText: "Misschien is hij verplaatst. Ga terug naar de start.",
    backHome: "Terug naar home",
    toFill: "Nog in te vullen",
    results: "resultaten",
    result: "resultaat",
    all: "Alles",
  },
  home: {
    greeting: "Bon bini bij Kas Daas",
    welcomeGuest: "Welkom in Kas Daas, {name}",
    tagline: "Jouw plek op Bonaire.",
    intro: "Alles voor een heerlijk verblijf — de villa, onze favoriete plekken en de boot. Altijd bij de hand, ook offline.",
    quick: "Snel naar",
    yourStay: "Jouw verblijf",
    arrival: "Aankomst",
    departure: "Vertrek",
    checkout: "Check-out",
    contactHost: "Contact host",
    discover: "Ontdek Bonaire",
    discoverText: "Onze persoonlijke tips, van rif tot restaurant.",
    villaGuide: "Villa-gids",
    villaGuideText: "Hoe alles werkt in Kas Daas.",
    ourBoat: "Onze boot",
    ourBoatText: "Bonaire vanaf het water.",
    favourites: "Kas Daas favorieten",
    favouritesText: "Plekken waar we zelf steeds weer naartoe gaan.",
    today: "Vandaag op Bonaire",
    todayMorning: "Goedemorgen. Snorkelen is ’s ochtends op z’n mooist.",
    todayAfternoon: "Middagzon? Tijd voor schaduw, lunch of Lac Bay.",
    todayEvening: "De zon gaat bijna onder. Waar kijk jij?",
    todayNight: "Tijd voor diner — of een rustige avond op het terras.",
    tonight: "Vanavond",
    tonightText: "Diner- en sunsetplekken die we aanraden.",
    dontMiss: "Niet missen",
    goodToKnow: "Handig om te weten",
    fromTheVilla: "Vanuit de villa",
    plans: "De perfecte dag op Bonaire",
    plansText: "Kant-en-klare dagplannen voor elk humeur.",
    install: "Kas Daas altijd bij de hand?",
    tipSun: "Zon",
    tipSunText: "Sterker dan je denkt",
    tipNature: "Natuur beschermen",
    tipNatureText: "Het rif is beschermd",
    tipMoney: "Geld & pinnen",
    tipMoneyText: "Amerikaanse dollar",
    tipTime: "Tijdzone",
    tipTimeText: "UTC−4, geen zomertijd",
  },
  quick: {
    about: "Over Kas Daas",
    wifi: "WiFi",
    route: "Route",
    food: "Eten & drinken",
    discover: "Ontdek Bonaire",
    boat: "Huur onze boot",
    help: "Hulp & contact",
    checkout: "Check-out",
  },
  villa: {
    title: "Villa-gids",
    subtitle: "Alles over Kas Daas, mooi op een rij.",
    duringStay: "Tijdens je verblijf",
    departureTitle: "Vertrek",
    departureSub: "Check-out checklist",
    helpTitle: "Hulp & problemen",
    helpSub: "Wat te doen als…",
    wifiTitle: "WiFi",
    wifiSub: "Netwerk & wachtwoord",
    confirmPresence: "Aanwezigheid nog te bevestigen",
    topics: "onderwerpen",
    steps: "Zo werkt het",
  },
  wifi: {
    network: "Netwerk",
    password: "Wachtwoord",
    copyPassword: "Kopieer wachtwoord",
    scan: "Scan om direct te verbinden",
    scanHint: "Open de camera op je telefoon en richt op de code.",
    coverage: "Bereik",
    router: "Router & storing",
    notSet: "Het wifi-wachtwoord wordt nog ingevuld door de beheerder.",
  },
  departure: {
    title: "Vertrek",
    subtitle: "Check-out zonder zorgen",
    checkoutTime: "Check-outtijd",
    progress: "{done} van {total} gedaan",
    allDone: "Alles gedaan — goede reis!",
    resetList: "Lijst wissen",
  },
  help: {
    title: "Hulp & contact",
    subtitle: "We zijn er als je ons nodig hebt.",
    host: "Jouw host",
    availability: "Bereikbaarheid",
    emergency: "Noodnummers",
    emergencyText: "Bij direct gevaar: bel het alarmnummer.",
    problems: "Wat te doen als…",
    tryFirst: "Probeer eerst",
    stillStuck: "Lukt het niet?",
    messageHost: "Stuur de host een bericht",
    email: "E-mail",
    needHelp: "Hulp nodig?",
  },
  discover: {
    title: "Ontdek Bonaire",
    subtitle: "Ons Bonaire — plekken die we zelf graag bezoeken.",
    categories: "Categorieën",
    favourites: "Kas Daas favorieten",
    placesWeLove: "Plekken waar we van houden",
    filterTags: "Filter",
    empty: "Geen plekken gevonden. Probeer een ander filter.",
    map: "Kaart",
    plans: "Dagplannen",
    restaurants: "Restaurantgids",
    restaurantsText: "Handpicked restaurants — van strandlunch tot sunset-diner.",
    ourFavourites: "Onze favorieten",
    worthTheDrive: "Het ritje waard",
    perfectSunset: "Perfect voor sunset",
    searchIn: "Zoek in deze categorie",
  },
  place: {
    why: "Waarom wij dit aanraden",
    whyGo: "Waarom gaan?",
    oneOfOurFavourites: "Een van onze favorieten",
    kasDaasRecommends: "Kas Daas raadt aan",
    cuisine: "Keuken",
    price: "Prijsklasse",
    reservation: "Reserveren aanbevolen",
    yes: "Ja",
    no: "Nee",
    unknown: "Onbekend",
    location: "Locatie",
    travelTime: "Reistijd vanaf Kas Daas",
    hours: "Openingstijden",
    practicalTip: "Praktische tip",
    goodToKnow: "Goed om te weten",
    activity: "Zo haal je er het meeste uit",
    whyFun: "Waarom is dit leuk?",
    forWho: "Voor wie?",
    duration: "Hoeveel tijd?",
    bring: "Wat neem je mee?",
    bestTime: "Beste moment",
    diyOrBook: "Zelf doen of boeken?",
    keepInMind: "Waar let je op?",
    approximate: "Locatie bij benadering",
    related: "Ook de moeite waard",
    shareText: "Tip van Kas Daas:",
  },
  plans: {
    title: "Dagplannen",
    subtitle: "Inspiratie voor een perfecte dag — neem wat je leuk vindt.",
    day: "Dag",
    open: "Bekijk plan",
    suggestion: "Tijden zijn suggesties — op Bonaire heb je geen haast.",
  },
  map: {
    title: "Kaart",
    subtitle: "Onze tips op de kaart, met Kas Daas als thuisbasis.",
    home: "Kas Daas — thuisbasis",
    homePlaceholder: "Locatie van Kas Daas volgt",
    offline: "De kaartachtergrond heeft internet nodig. De lijst hieronder werkt altijd.",
    list: "Lijst",
    details: "Details",
    locate: "Mijn locatie",
  },
  favorites: {
    title: "Mijn Bonaire",
    subtitle: "Jouw bewaarde plekken, op dit apparaat.",
    empty: "Nog niets bewaard. Tik op het hartje bij een plek om hem hier te bewaren.",
    recent: "Recent bekeken",
    explore: "Ontdek plekken",
    add: "Bewaar in Mijn Bonaire",
    removeFav: "Verwijder uit Mijn Bonaire",
  },
  search: {
    title: "Zoeken",
    hint: "Probeer: wifi, airco, check-out, pizza, snorkelen, boot, supermarkt",
    none: "Niets gevonden voor “{q}”.",
    noneHint: "Probeer een ander woord, of vraag het de host.",
    types: { villa: "Villa", place: "Plek", plan: "Dagplan", practical: "Goed om te weten", help: "Hulp", boat: "Boot", page: "Pagina" },
  },
  more: {
    title: "Meer",
    subtitle: "Alles wat je verder nodig hebt.",
    guide: "Gids",
    app: "App",
    install: "Zet op beginscherm",
    installed: "Geïnstalleerd",
    about: "Over deze gids",
    aboutText: "Deze gids is gemaakt door de eigenaren van Kas Daas. Tips zijn persoonlijk — geen advertenties, geen ratings.",
    clearData: "Wis mijn gegevens op dit apparaat",
    clearDataText: "Favorieten, checklists en naam worden verwijderd.",
    cleared: "Gewist",
    offlineReady: "Klaar voor offline gebruik",
    offlineNotReady: "Offline opslag wordt voorbereid…",
  },
  practical: {
    title: "Goed om te weten op Bonaire",
    subtitle: "Praktische info voor een zorgeloze vakantie.",
    places: "Adressen",
  },
  install: {
    title: "Kas Daas altijd bij de hand?",
    text: "Zet de gids op je beginscherm. Hij opent dan als app — ook zonder internet.",
    button: "Zet op beginscherm",
    later: "Later",
    iosStep1: "Tik op Deel",
    iosStep2: "Kies ‘Zet op beginscherm’",
    iosHint: "In Safari, onderin je scherm",
  },
  boat: {
    rent: "Huur onze boot",
    facts: "Goed om te weten",
    included: "Inbegrepen",
    conditions: "Voorwaarden",
    ideas: "Ideeën voor een dag op het water",
    contact: "Stel je vraag via WhatsApp",
    call: "Bel ons",
    linkInvalid: "Deze bootlink is niet (meer) geldig. Neem contact op met de host voor een nieuwe link.",
  },
  boatGuide: {
    sos: "SOS / Hulp nodig",
    sosTitle: "Hulp nodig op het water?",
    sosText: "Blijf rustig. Zorg dat iedereen een reddingsvest draagt. Bel bij direct gevaar het alarmnummer.",
    sections: "Inhoud",
    location: "Waar ligt de boot",
    before: "Voor vertrek",
    start: "Boot starten",
    controls: "Bediening",
    safety: "Veiligheid",
    area: "Vaargebied",
    mooring: "Ankeren & aanleggen",
    anchoring: "Ankeren",
    docking: "Aanleggen",
    return: "Terugkomst",
    problems: "Problemen",
    contacts: "Contact",
    mediaSoon: "Foto/video volgt",
    areaSoon: "De kaart met het vaargebied wordt door de beheerder ingevuld.",
    solved: "Opgelost — goede vaart!",
    contactOwner: "Neem contact op met de beheerder",
    startOver: "Opnieuw",
    validUntil: "Toegang geldig tot",
    privateNote: "Deze pagina is privé en alleen voor huurders van de boot. Deel de link niet.",
    offlineSaved: "Deze handleiding is ook offline beschikbaar op dit apparaat tot je toegang verloopt.",
    forget: "Verwijder boot-info van dit apparaat",
    forgotten: "Verwijderd",
    zones: { allowed: "Toegestaan", forbidden: "Niet toegestaan", shallow: "Ondiep", danger: "Gevaarlijk", mooring: "Aanleggen / ankeren", poi: "Handige plek" },
    rules: "Aanleg- en ankerregels",
  },
};

type Dict = typeof nl;
type DeepString<T> = { [K in keyof T]: T[K] extends string ? string : DeepString<T[K]> };

const en: DeepString<Dict> = {
  brand: {
    recommends: "Kas Daas recommends",
    ourBonaire: "Our Bonaire",
    handpicked: "Handpicked",
    roadTrip: "Road trip",
    hiddenGems: "Hidden gems",
    perfectDay: "Perfect day on Bonaire",
    private: "Private",
  },
  nav: { home: "Home", villa: "Villa", discover: "Discover", boat: "Boat", more: "More" },
  common: {
    search: "Search",
    searchPlaceholder: "Search wifi, air con, pizza, snorkeling…",
    back: "Back",
    home: "Home",
    route: "Directions",
    call: "Call",
    whatsapp: "WhatsApp",
    website: "Website",
    reserve: "Reserve",
    share: "Share",
    copy: "Copy",
    copied: "Copied",
    viewAll: "View all",
    more: "More",
    close: "Close",
    open: "Open",
    save: "Save",
    saved: "Saved",
    remove: "Remove",
    demo: "Sample — to be verified",
    photoSoon: "Photo coming soon",
    needsInternet: "Needs internet",
    offline: "Offline — you're viewing saved info",
    backOnline: "Back online",
    language: "Language",
    toTop: "Back to top",
    minutes: "min",
    step: "Step",
    tip: "Tip",
    reset: "Reset",
    done: "Done",
    of: "of",
    notFoundTitle: "This page doesn't exist",
    notFoundText: "It may have moved. Head back to the start.",
    backHome: "Back to home",
    toFill: "To be filled in",
    results: "results",
    result: "result",
    all: "All",
  },
  home: {
    greeting: "Bon bini to Kas Daas",
    welcomeGuest: "Welcome to Kas Daas, {name}",
    tagline: "Your private place on Bonaire.",
    intro: "Everything for a wonderful stay — the villa, our favourite places and the boat. Always at hand, even offline.",
    quick: "Quick access",
    yourStay: "Your stay",
    arrival: "Arrival",
    departure: "Departure",
    checkout: "Check-out",
    contactHost: "Contact host",
    discover: "Discover Bonaire",
    discoverText: "Our personal picks, from reef to restaurant.",
    villaGuide: "Villa guide",
    villaGuideText: "How everything works at Kas Daas.",
    ourBoat: "Our boat",
    ourBoatText: "Bonaire from the water.",
    favourites: "Kas Daas favourites",
    favouritesText: "Places we keep going back to ourselves.",
    today: "Today on Bonaire",
    todayMorning: "Good morning. Snorkeling is at its best in the morning.",
    todayAfternoon: "Afternoon sun? Time for shade, lunch or Lac Bay.",
    todayEvening: "The sun is about to set. Where will you watch it?",
    todayNight: "Time for dinner — or a quiet evening on the terrace.",
    tonight: "Tonight",
    tonightText: "Dinner and sunset spots we recommend.",
    dontMiss: "Don't miss",
    goodToKnow: "Good to know",
    fromTheVilla: "From the villa",
    plans: "Perfect day on Bonaire",
    plansText: "Ready-made day plans for every mood.",
    install: "Keep Kas Daas at hand?",
    tipSun: "Sun",
    tipSunText: "Stronger than you think",
    tipNature: "Protect nature",
    tipNatureText: "The reef is protected",
    tipMoney: "Money & cards",
    tipMoneyText: "US dollar",
    tipTime: "Time zone",
    tipTimeText: "UTC−4, no daylight saving",
  },
  quick: {
    about: "About Kas Daas",
    wifi: "WiFi",
    route: "Directions",
    food: "Eat & drink",
    discover: "Discover Bonaire",
    boat: "Rent our boat",
    help: "Help & contact",
    checkout: "Check-out",
  },
  villa: {
    title: "Villa guide",
    subtitle: "Everything about Kas Daas, beautifully in one place.",
    duringStay: "During your stay",
    departureTitle: "Departure",
    departureSub: "Check-out checklist",
    helpTitle: "Help & issues",
    helpSub: "What to do if…",
    wifiTitle: "WiFi",
    wifiSub: "Network & password",
    confirmPresence: "Availability to be confirmed",
    topics: "topics",
    steps: "How it works",
  },
  wifi: {
    network: "Network",
    password: "Password",
    copyPassword: "Copy password",
    scan: "Scan to connect instantly",
    scanHint: "Open your phone's camera and point it at the code.",
    coverage: "Coverage",
    router: "Router & outages",
    notSet: "The WiFi password will be added by the host.",
  },
  departure: {
    title: "Departure",
    subtitle: "A worry-free check-out",
    checkoutTime: "Check-out time",
    progress: "{done} of {total} done",
    allDone: "All done — safe travels!",
    resetList: "Clear list",
  },
  help: {
    title: "Help & contact",
    subtitle: "We're here when you need us.",
    host: "Your host",
    availability: "Availability",
    emergency: "Emergency numbers",
    emergencyText: "In immediate danger: call the emergency number.",
    problems: "What to do if…",
    tryFirst: "Try this first",
    stillStuck: "Still stuck?",
    messageHost: "Message the host",
    email: "Email",
    needHelp: "Need help?",
  },
  discover: {
    title: "Discover Bonaire",
    subtitle: "Our Bonaire — places we love to visit ourselves.",
    categories: "Categories",
    favourites: "Kas Daas favourites",
    placesWeLove: "Places we love",
    filterTags: "Filter",
    empty: "No places found. Try another filter.",
    map: "Map",
    plans: "Day plans",
    restaurants: "Restaurant guide",
    restaurantsText: "Handpicked restaurants — from beach lunch to sunset dinner.",
    ourFavourites: "Our favourites",
    worthTheDrive: "Worth the drive",
    perfectSunset: "Perfect for sunset",
    searchIn: "Search this category",
  },
  place: {
    why: "Why we recommend it",
    whyGo: "Why go?",
    oneOfOurFavourites: "One of our favourites",
    kasDaasRecommends: "Kas Daas recommends",
    cuisine: "Cuisine",
    price: "Price range",
    reservation: "Reservation recommended",
    yes: "Yes",
    no: "No",
    unknown: "Unknown",
    location: "Location",
    travelTime: "Travel time from Kas Daas",
    hours: "Opening hours",
    practicalTip: "Practical tip",
    goodToKnow: "Good to know",
    activity: "Making the most of it",
    whyFun: "Why it's great",
    forWho: "Who is it for?",
    duration: "How long?",
    bring: "What to bring",
    bestTime: "Best time",
    diyOrBook: "DIY or book?",
    keepInMind: "Keep in mind",
    approximate: "Approximate location",
    related: "Also worth it",
    shareText: "A tip from Kas Daas:",
  },
  plans: {
    title: "Day plans",
    subtitle: "Inspiration for a perfect day — take what you like.",
    day: "Day",
    open: "View plan",
    suggestion: "Times are suggestions — there's no rush on Bonaire.",
  },
  map: {
    title: "Map",
    subtitle: "Our tips on the map, with Kas Daas as your home base.",
    home: "Kas Daas — home base",
    homePlaceholder: "Kas Daas location coming soon",
    offline: "The map background needs internet. The list below always works.",
    list: "List",
    details: "Details",
    locate: "My location",
  },
  favorites: {
    title: "My Bonaire",
    subtitle: "Your saved places, on this device.",
    empty: "Nothing saved yet. Tap the heart on any place to keep it here.",
    recent: "Recently viewed",
    explore: "Explore places",
    add: "Save to My Bonaire",
    removeFav: "Remove from My Bonaire",
  },
  search: {
    title: "Search",
    hint: "Try: wifi, air con, check-out, pizza, snorkeling, boat, supermarket",
    none: "Nothing found for “{q}”.",
    noneHint: "Try another word, or ask the host.",
    types: { villa: "Villa", place: "Place", plan: "Day plan", practical: "Good to know", help: "Help", boat: "Boat", page: "Page" },
  },
  more: {
    title: "More",
    subtitle: "Everything else you might need.",
    guide: "Guide",
    app: "App",
    install: "Add to home screen",
    installed: "Installed",
    about: "About this guide",
    aboutText: "This guide was made by the owners of Kas Daas. Our tips are personal — no ads, no ratings.",
    clearData: "Clear my data on this device",
    clearDataText: "Favourites, checklists and your name will be removed.",
    cleared: "Cleared",
    offlineReady: "Ready for offline use",
    offlineNotReady: "Preparing offline storage…",
  },
  practical: {
    title: "Good to know on Bonaire",
    subtitle: "Practical info for a carefree holiday.",
    places: "Addresses",
  },
  install: {
    title: "Keep Kas Daas at hand?",
    text: "Add the guide to your home screen. It then opens like an app — even without internet.",
    button: "Add to home screen",
    later: "Later",
    iosStep1: "Tap Share",
    iosStep2: "Choose ‘Add to Home Screen’",
    iosHint: "In Safari, at the bottom of your screen",
  },
  boat: {
    rent: "Rent our boat",
    facts: "Good to know",
    included: "Included",
    conditions: "Conditions",
    ideas: "Ideas for a day on the water",
    contact: "Ask us on WhatsApp",
    call: "Call us",
    linkInvalid: "This boat link is no longer valid. Please contact the host for a new link.",
  },
  boatGuide: {
    sos: "SOS / Need help",
    sosTitle: "Need help on the water?",
    sosText: "Stay calm. Make sure everyone wears a life jacket. In immediate danger, call the emergency number.",
    sections: "Contents",
    location: "Where the boat is",
    before: "Before you leave",
    start: "Starting the boat",
    controls: "Controls",
    safety: "Safety",
    area: "Boating area",
    mooring: "Anchoring & docking",
    anchoring: "Anchoring",
    docking: "Docking",
    return: "Coming back",
    problems: "Problems",
    contacts: "Contact",
    mediaSoon: "Photo/video coming soon",
    areaSoon: "The boating area map will be added by the owner.",
    solved: "Solved — enjoy the water!",
    contactOwner: "Contact the owner",
    startOver: "Start over",
    validUntil: "Access valid until",
    privateNote: "This page is private and only for boat renters. Please don't share the link.",
    offlineSaved: "This manual is also available offline on this device until your access expires.",
    forget: "Remove boat info from this device",
    forgotten: "Removed",
    zones: { allowed: "Permitted", forbidden: "Not permitted", shallow: "Shallow", danger: "Dangerous", mooring: "Mooring / anchoring", poi: "Useful spot" },
    rules: "Mooring and anchoring rules",
  },
};

export const dictionaries = { nl, en };
export type Dictionary = DeepString<Dict>;

/** Replace {placeholders} in a string. */
export function fmt(template: string, vars: Record<string, string | number>): string {
  return template.replace(/\{(\w+)\}/g, (_, k) => String(vars[k] ?? ""));
}
